### ISSUE TITLE
List of papers that are not exported correctly

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#107]
There's a list of papers that fail to export, and I'm opening this ticket to keep track of what's going on. Most of these papers fail with the error `NoMethodError: undefined method 'title' for nil:NilClass`, which is an error that doesn't make sense because those papers *do* have titles. Seeing as how most of them end in 000 (see the list down below), I believe there's an issue with papers that represent volumes rather than single entries.

I'll look deeper into this.

Here's the list of paper IDs that fail to export properly:

  * **C69:** 0100, 0101, 0200, 0201, 0300, 0301, 0400, 0401, 0500, 0501, 0600, 0601, 0700, 0701, 0800, 0801, 0900, 0901
 * **J00:** 1000, 2000, 3000, 4000
 * **J01:** 1000, 2000, 3000, 4000
 * **J02:** 1000, 2000, 3000, 4000
 * **J03:** 1000, 2000, 3000, 4000
 * **J04:** 1000, 2000, 3000, 4000
 * **J05:** 1000, 2000, 3000, 4000
 * **J06:** 1000, 2000, 3000, 4000
 * **J07:** 1000, 2000, 3000, 4000
 * **J08:** 1000, 2000, 3000, 4000
 * **J09:** 1000, 2000, 3000, 4000
 * **J10:** 1000, 2000, 3000, 4000
 * **J11:** 1000, 2000, 3000, 4000
 * **J12:** 1000, 2000, 3000, 4000
 * **J13:** 1000, 2000, 3000, 4000
 * **J14:** 1000, 2000, 3000, 4000
 * **J15:** 1000, 2000, 3000, 4000
 * **J16:** 1000, 2000, 3000, 4000
 * **J17:** 1000, 2000, 3000, 4000
 * **J18:** 1000, 2000, 3000, 4000
 * **J79:** 1000
 * **J80:** 1000, 2000, 3000
 * **J81:** 1000, 2000, 3000, 4000
 * **J82:** 1000, 2000, 3000
 * **J83:** 1000, 2000, 3000
 * **J84:** 1000, 2000, 3000
 * **J85:** 1000, 2000, 4000
 * **J86:** 1000, 2000, 3000, 4000
 * **J87:** 1000, 3000
 * **J88:** 1000, 2000, 3000, 4000
 * **J89:** 1000, 2000, 3000, 4000
 * **J90:** 1000, 2000, 3000, 4000
 * **J91:** 1000, 2000, 3000, 4000
 * **J92:** 1000, 2000, 3000, 4000
 * **J93:** 1000, 2000, 3000, 4000
 * **J94:** 1000, 2000, 3000, 4000
 * **J95:** 1000, 2000, 3000, 4000
 * **J96:** 1000, 2000, 3000, 4000
 * **J97:** 1000, 2000, 3000, 4000
 * **J98:** 1000, 2000, 3000, 4000
 * **J99:** 1000, 2000, 3000, 4000

**Comment by mjpost** [comment]
Thanks for cataloguing this! Ideally we would not print the PDF (or bib) links if the URLs don't resolve.

**Comment by mbollmann** [comment]
The **C69** issue is a consequence of faulty XML, in my opinion. In the database import script, IDs of the form "x000" get interpreted as proceedings volumes, except for workshops, where it is IDs of the form "xx00". In `C69.xml`, volumes follow the workshop format, which leads to the first nine papers being ignored until a "proper" volume ID (1000) is found.

However, IMHO, the actual issue is that each paper has its own proceedings entry, which doesn't seem correct or useful to me. I believe the file should have a single proceedings entry with ID 1000, and the individual papers should be renumbered 0101 -> 1001, 0201 -> 1002, 0301 -> 1003, and so on.

**Comment by mjpost** [comment]
This seems right to me about C69. I just created an issue (#147) for it specifically, since it will require hand-correction.

**Comment by mjpost** [comment]
I believe these were all fixed with #324, in which I checked whether the frontmatter PDF existed and removed the `<url>` tag if not.
