### ISSUE TITLE
An alternative to joint.yaml

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#1164]
The [data/yaml/joint.yaml](https://github.com/acl-org/acl-anthology/blob/master/data/yaml/joint.yaml) file is a repeated source of confusion. While @mjpost recently started a [wiki page](https://github.com/acl-org/acl-anthology/wiki/Venues,-Volumes,-and-Events) that (also) describes how it's used, I wonder if we shouldn't refactor this to put the relevant information directly into the XML.

### Issues

Volumes are always implicitly linked to a venue through their Anthology ID. For example, [2020.blackboxnlp-1](https://www.aclweb.org/anthology/volumes/2020.blackboxnlp-1/) will be linked to "blackboxnlp"; [W19-48](https://www.aclweb.org/anthology/volumes/W19-48/) will be linked to "ws", which is the generic catch-all for workshops. Sometimes this one-to-one mapping is insufficient, which is why `joint.yaml` exists – it allows creating _additional_ mappings, e.g. to also associate with W19-48 with "blackboxnlp" and "acl" (as it took place during the ACL conference).

Some issues with this system have come up:

1. It is easy to forget to add entries to `joint.yaml` when ingesting new proceedings, e.g. causing workshops to not be accessible on the website via its parent conference or the generic "WS" entry (e.g. #1117). It's my impression that this is because the system is unintuitive.
2. It's not possible to distinguish between _joint_ events and _co-located_ events. (e.g., P15-1 is _joint_ with "ijcnlp", but W19-48 is _co-located_ with "acl")
3. There appear to some edge cases where the implicit linking might also be undesirable, e.g. #680 

### Alternative

There's nothing in `joint.yaml` that couldn't be represented directly in the XML itself. Since the logic of `joint.yaml` operates on the _volume level_, we could add this to a `<volume>`s `<meta>` block, like so:

```xml
  <volume id="48">
    <meta>
      <booktitle>Proceedings of the 2019 ACL Workshop BlackboxNLP: Analyzing and Interpreting Neural Networks for NLP</booktitle>
      <url hash="1c4c6922">W19-48</url>
         ...
      <venue>ws</venue>
      <venue>blackboxnlp</venue>
      <colocated>acl</colocated>
    </meta>
```

I would even suggest making it a requirement that at least one `<venue>` tag be present, i.e. to remove the implicit inference via the Anthology ID (remember the Zen of Python: _"Explicit is better than implicit."_). This way it's easy to see the exact set of venues or colocated events right in the XML file (and also to address edge cases like #680).

We could also discuss whether to do away with the generic "ws" venue and represent this some other way, e.g. as an attribute (`<volume id="48" is-workshop="1">`) or an empty meta-tag (`<is-workshop/>`). This might be helpful for refactoring the front page and how we present events there, for example. Also, "ws" is the only "venue" defined in `venues.yaml` that isn't actually a venue, but a catch-all category.

- - -

I would be happy to implement these changes, as I think that should be relatively straightforward.

**Comment by nschneid** [comment]
Note that it would be good to have documentation of sigs as well.

**Comment by mbollmann** [comment]
True, the association of volumes to SIGs works quite similarly to `joint.yaml`, so the information from those YAML files could be merged into the XML as well.

**Comment by mjpost** [comment]
I like the extended XML and even removing joint.xml, but I don’t like the idea of WS as a pseudo venue. Why not add a type field to venues.yaml that defaults to “workshop”? Then we could infer the association for both new and old style ids. 

A complicating factor is workshops that become conferences, e.g., EMNLP and WMT. 

What strikes me though is that we are missing events as a first order object. An event ties together multiple venues, volumes, and even papers (e.g., TACL). joint.xml is nice because it provides a quick event centric view of a conference. But that may be out of scope for goals and needs. I also hate the idea of having to reconstruct all that for past events and of chasing down that info for volumes we host outside our community. It’s already a bit of a hassle handling venue ids for all the workshops.

**Comment by mbollmann** [comment]
> I like the extended XML and even removing joint.xml, but I don’t like the idea of WS as a pseudo venue. Why not add a type field to venues.yaml that defaults to “workshop”? Then we could infer the association for both new and old style ids.

I like the idea of a type field that could be e.g. "workshop", "conference", or "journal". But basically that would mean moving the workshop tag from the volume level to the venue level. Technically that would work as long as all "W"-volumes have another venue associated with them that's not WS. I just fear it could complicate determining the "type" of volumes that are tagged with multiple venues, introducing some non-explicit inference again.

> What strikes me though is that we are missing events as a first order object. An event ties together multiple venues, volumes, and even papers (e.g., TACL). joint.xml is nice because it provides a quick event centric view of a conference.

I agree, we basically don't keep track of events, although introducing a separate `<colocated>` tag would make this a bit cleaner already. It would be a more pressing issue if we ever had a conference that does more than one event per year...

**Comment by mjpost** [comment]
I like the idea of moving the contents of `joint.yaml` into the XML as proposed, but it seems to me to be a sideways move, or at best a small step forward. The volumes are not “colocated”; rather, they were presented together at a physical event, and the existence of that event is currently inferred. The solution here furthermore marks just the main (or first) volume in a collection as `colocated` or `joint`; what about the other volumes in the collection? Do we infer their joint status by virtue of them being listed in the same collection as the main volume?

In the spirit of “explicit is better”, it seems better to me to explicitly represent events. One proposal would be 

* Create a `data/events/` directory, and use the current event names, e.g., `emnlp-2021` would be in `2021-emnlp.xml`
* This file would have minimal information, such as where it was held, when, etc
* It would also host entries for data associated with the event itself, e.g., keynotes, the handbook, and other such items (#298)
* Dump our current inferences to this new explicit representation

This would be a bigger step forward in terms of the representational capacity of the Anthology, and would solve a big open problem (i.e., #298).

What do you think? I’d be open to making this a big short-term priority, and could contribute some time to it over the next two months, if needed. Maybe we should have a half hour meeting about this since it seems to be percolating up to the top of the todo list.

**Comment by mbollmann** [comment]
Thanks for your thoughts, Matt!

I've been shying away from the refactoring effort this might take, but it probably is the right way forward, as it might also allow us to present the event pages better (e.g., ordering of the proceedings volumes). I'm happy to find a time to discuss this, although the coming weeks are a bit busy. Do you want to initiate a Doodle or something?

**Comment by nschneid** [comment]
One request for this is to make it possible to standardize the location/address field across venues at an event. E.g. I noticed that [BlackboxNLP 2021](https://aclanthology.org/volumes/2021.blackboxnlp-1/) has "Punta Cana, Dominican Republic" in the metadata and "Online" in the PDF footer, as opposed to the main conference (EMNLP) which has "Online and Punta Cana, Dominican Republic".

**Comment by mjpost** [comment]
I too am bothered by these inconsistencies, but in the end it's not our role (nor within our bandwidth) to enforce them. I often give advice to submitters (I tried to have "Online and" struck from the EMNLP location, for example), but in the end, it's up to them.

Though this seems more relevant to ACLPUB. You might be interested in the [aclpub2 effort](https://github.com/rycolab/aclpub2), which is rewriting ACLPUB in preparation for ACL's and NAACL's transition to ARR next year.

**Comment by mbollmann** [comment]
Just a note that if we're going to refactor this as described by Matt, I'd also be in favor of prioritizing this now. Lately I've been thinking about both the search functionality and the front page redesign (the two most important usability issues of the Anthology in my opinion), and I feel both don't make sense to tackle right now before we've implemented this.

**Comment by mjpost** [comment]
I agree the time is right for this. It addresses a core archival need that is currently and increasingly egregiously lacking. Let’s move it to the top of the queue, and then we can tackle the usability issues.

**Comment by mjpost** [comment]
I just sent a when2meet poll to @mbollmann and @akoehn. Anyone else who is interested in trying to join, please ping me.
