### ISSUE TITLE
Bug report: Inconsistent bibtex key for papers with similar prefix

### ISSUE THREAD

**Issue by VisualJoyce** [acl-org/acl-anthology#1236]
*Use this issue template to help file your issue. Please delete portions that are not relevant, and feel free to change it or add sections.*

#### Issue description
In an earlier version of `anthology.bib`, the key prefix `wang-etal-2017-deep` has the following candidates.

```bibtex
@inproceedings{wang-etal-2017-deep,
    title = "Deep Neural Machine Translation with Linear Associative Unit",
    author = "Wang, Mingxuan  and
      Lu, Zhengdong  and
      Zhou, Jie  and
      Liu, Qun",
    booktitle = "Proceedings of the 55th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)",
    month = jul,
    year = "2017",
    address = "Vancouver, Canada",
    publisher = "Association for Computational Linguistics",
    url = "https://www.aclweb.org/anthology/P17-1013",
    doi = "10.18653/v1/P17-1013",
    pages = "136--145",
}

@inproceedings{wang-etal-2017-deep-neural,
    title = "Deep Neural Solver for Math Word Problems",
    author = "Wang, Yan  and
      Liu, Xiaojiang  and
      Shi, Shuming",
    booktitle = "Proceedings of the 2017 Conference on Empirical Methods in Natural Language Processing",
    month = sep,
    year = "2017",
    address = "Copenhagen, Denmark",
    publisher = "Association for Computational Linguistics",
    url = "https://www.aclweb.org/anthology/D17-1088",
    doi = "10.18653/v1/D17-1088",
    pages = "845--854",
}
```

Using the latest `anthology.bib.gz`, the same key prefix leads to different orders of the papers
```bibtex
@inproceedings{wang-etal-2017-deep-neural,
    title = "Deep Neural Machine Translation with Linear Associative Unit",
    author = "Wang, Mingxuan  and
      Lu, Zhengdong  and
      Zhou, Jie  and
      Liu, Qun",
    booktitle = "Proceedings of the 55th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)",
    month = jul,
    year = "2017",
    address = "Vancouver, Canada",
    publisher = "Association for Computational Linguistics",
    url = "https://www.aclweb.org/anthology/P17-1013",
    doi = "10.18653/v1/P17-1013",
    pages = "136--145",
}

@inproceedings{wang-etal-2017-deep,
    title = "Deep Neural Solver for Math Word Problems",
    author = "Wang, Yan  and
      Liu, Xiaojiang  and
      Shi, Shuming",
    booktitle = "Proceedings of the 2017 Conference on Empirical Methods in Natural Language Processing",
    month = sep,
    year = "2017",
    address = "Copenhagen, Denmark",
    publisher = "Association for Computational Linguistics",
    url = "https://www.aclweb.org/anthology/D17-1088",
    doi = "10.18653/v1/D17-1088",
    pages = "845--854",
}

```

This proves that it's not consistent when generating bibtex keys for each paper, at least for very similar prefixes, the generation is not ordered.

This is a potential issue may lead to miscitation in real usage. 

#### What's the expected result?

The key should be unique as well as consistent across different releases.

#### What's the actual result?

The bibtex key will change across different releases.

**Comment by mbollmann** [comment]
Thanks for the report! I think you raise an important issue here, especially as the full Anthology bib-file is now distributed with conference templates.

In the code, BibTeX keys are generated on-the-fly when the XML files are parsed. So one way to make them deterministic would be to ensure that XML files are always processed in the same order here:

https://github.com/acl-org/acl-anthology/blob/b26270386b65c0861d17d4d6d5d7a1eaf345499f/bin/anthology/anthology.py#L56

However, to ensure that keys don't change when new volumes are added, the ordering would have to be by ingestion date somehow, with newer volumes always coming later. But even then, BibTeX keys could theoretically change e.g. when a paper is removed (due to retraction etc.).

A better alternative to ensure consistency might be to record these keys in the XML, and move their generation to the ingestion pipeline. @akoehn? @mjpost?

**Comment by akoehn** [comment]
> A better alternative to ensure consistency might be to record these
> keys in the XML, and move their generation to the ingestion
> pipeline. @akoehn? @mjpost?

i think that this is the correct way if we want to ensure consistency
over time – but it will require quite some engineering effort.

**Comment by mbollmann** [comment]
> i think that this is the correct way if we want to ensure consistency over time – but it will require quite some engineering effort.

What are the challenges you see? It seems quite straightforward to me, as the BibTeX key logic is encapsulated in our classes, so the change is limited to one place in the code (+ making sure we add the generation to the ingestion scripts).

**Comment by mjpost** [comment]
Wow, I hadn't considered this at all. I've also been thinking it might be nice to have the venue ID as part of the key (e.g., `post-etal-2021.acl-principia`), but this makes me think we shouldn't change it. This is a good reminder to take care when creating outward-facing decisions (FTR I think we did well here).

One challenge is to define a stable processing order. Let's say we use (year, ingestion date, volume acronym) as the sort key. What happens if someone adds or changes the ingestion date of an existing volume? Most volumes have no ingestion date, but if someone were to go and back-add that (say, for copyright or patent reasons), it could alter the order. There is no way to 

This causes me to agree with @akoehn that we should probably explicitly add the key, and ensure uniqueness when adding new keys.
