### ISSUE TITLE
Correction to Anthology ID 2021.teachingnlp-1.7

### ISSUE THREAD

**Issue by melfnt** [acl-org/acl-anthology#1334]
## Metadata correction: please describe the issue here**

We would like to link this repository as supplementary material: https://bitbucket.org/melfnt/malvisindi

The archive currently used as supplementary material (`2021.teachingnlp-1.7.OptionalSupplementaryMaterial.zip`) is the one we uploaded for the peer review process and it is therefore redacted, while the link proposed for replacement is the same we used in the camera-ready version (see footnote 4 of https://www.aclweb.org/anthology/2021.teachingnlp-1.7.pdf). Furthermore, we will continue to improve the repository on Bitbucket in the future, which is not possible with the "static" archive.

**Comment by mjpost** [comment]
Hi, we can't link to outside data resources. You can add a link to your paper and post a paper revision, if you want to link to an outside resource.

**Comment by melfnt** [comment]
Hi,

I understand. The link is also already in my paper.
The problem is that the material being currently used is both outdated 
and redacted for review. Can we post a newer version of the archive?

Thank you

**Comment by mjpost** [comment]
We aren't really setup to process updates to attachments. I expect most people will seek out the updated link in the paper. If you like, we can remove the attachment.

**Comment by akoehn** [comment]
... but we can remove and add attachments, which is effectively an update.

Side note:
I'm quite frankly not sure whether data and code attachments are well auited at the anthology; other sites provide such infrastructure already and maybe we should cooperate with them in the long term instead of trying to build infrastructure for automation.

**Comment by mjpost** [comment]
Yes, what I meant by not being setup, is that I don't want to take on this responsibility in general, since it requires volunteer time. I guess we could process this as a one-off, but I think it runs contrary to the idea of the Anthology, which is not to be the most up-to-date source of information. Pointing to external resources is nice, but aside from the time required under our current system, there is another issue, which is that from the Anthology's perspective, all external pointers are subject to bit-rot.

So @melfnt: to answer your question, the Anthology's purpose isn't to host cutting edge software, but to capture ideas as they were at a certain point in time (that time being the time of publication). I think this is common understanding. Since the link to the bitbucket repo is in the paper, I suggest you assume your readers will follow it for the most recent code.

**Comment by melfnt** [comment]
Ok then, thank you for your time
