### ISSUE TITLE
Correctly convert LaTeX to HTML

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#135]
Currently there are a few titles with LaTeX commands and special characters, which don't display correctly on the anthology website (for example, [here](https://aclanthology.info/papers/C12-2049/c12-2049).) This problem happens a lot more in abstracts, but as far as I can tell, those aren't displayed on the website.

@danielgildea has added [latex.py](https://github.com/acl-org/acl-anthology/commit/79fe2730257e9efbfb883d549c66087ab096e11f) presumably for this purpose, so I'm just creating an issue for it.

Some wrinkles to this issue:
- Papers prepared in Word may have a different set of special characters (esp. straight vs. curly apostrophes and quotes)
- What's the right representation for the XML sources that the HTML is derived from? Presumably we don't want a more drastic solution like MathML.
  * Characters like `\'{e}` have direct Unicode equivalents, even in (modern) LaTeX, so should be converted to Unicode.
  * Some math symbols, like `\rightarrow` have Unicode equivalents, but I'm not sure if converting them is right.
  * Actual math could be marked with a tag like `<latexmath>M^2</latexmath>`?
- How should math be rendered on web pages? MathJax/KaTeX are slow and could be overkill. I like how pandoc's default math renderer tries to use Unicode and HTML; it's very incomplete but probably enough.

**Comment by danielgildea** [comment]
One comment: unicode in bibtex files is generally not recommended because it breaks the sorting of  author names.

Another gotcha is that in bibtex you have to say 
` author = "J{\"u}rgen"`
or 
` author = {J\"urgen}`
but not
` author = "J\"urgen"`

that is why is used the "latex.py" rather than the "latexcodec" library

**Comment by davidweichiang** [comment]
It looks like JATS (https://jats.nlm.nih.gov/archiving/) uses <tex-math> for TeX formulas. Or <mml:math> for MathML, which actually doesn’t look so bad (Pandoc can convert to/from it, for instance).

**Comment by mjpost** [comment]
I'm happy to consider other proposals (since I could easily be missing something), but my vote is in favor of hosting properly-escaped raw BibTeX in the titles. While it makes sense to use UTF8 in the XML file, it might create some tricky conversion issues, especially when we encounter math, as you point out above. We are using XML as a more robust and extensible archival format for authoritative data, but we ingest from BibTeX, and BibTeX is our principal export format, so using raw BibTeX would avoid an error-prone double-conversion on titles. We would then need only worry about one conversion, when converting to MODS XML, which is used to generate the other citation formats.

**Comment by mbollmann** [comment]
I'm inclined to agree with Matt. If we interpret LaTeX in titles etc., 
that raises the need to constantly update the XML schema whenever new 
elements are introduced. For example, right now the schema allows 
`<sup>` because of a single paper that uses superscript "TM". And that's 
a simple case compared to, say, math formulas.

It would be easy to add BibTeX -> Unicode/HTML conversion to my Python 
wrapper in #133, and if we generated all non-BibTeX formats (website + 
MODS XML) from that wrapper, we could ensure consistency across all 
formats, and have a single place to fix any potential errors.

**Comment by davidweichiang** [comment]
My own inclination was to use Unicode outside of math formulas and TeX inside math formulas. For example, the superscript TM could have been represented by ™ (U+2122). That would have a simple schema. @mjpost's point about a pointless round-trip conversion stands, but on the other hand, consider that a minority of papers were never in LaTeX/BibTeX to begin with, and consider that arguably the main output format is HTML, not BibTeX.

But I agree that going all BibTeX is totally reasonable as well. It would require converting titles/abstracts not written using LaTeX/BibTeX so that they do, though.

**Comment by knmnyn** [comment]
I tend to agree with David on this.  Going UTF-8/16 will allow charsets
outside of what LaTeX handles to be faithfully rendered well without
needing to worry about escapes in any meta markup.
We now have papers that have emojis in their titles and we already handle
HanZi for Chinese titles from ROCLING using UTF-8, so from a standards
point of view we are already using it.

**Comment by mjpost** [comment]
It does make sense to use the encoding most natural to the format—I hadn't though of Emojis in titles, for example. If we can have good library calls for the LaTeX ↔︎ XML conversions, that will reduce the problem to a big single effort (which may be mostly done) and maybe occasional handling of new items as they arise. UTF-8 and structured XML titles will also help us avoid situations where titles contain curly braces that aren't intended to protect case, for example.

I'm surprised there is only a single instance of `<sup>`: I'd expect to see exponents, for example, so this may just reflect the fact that most titles are still some mix of LaTeX and plain text. I think we could limit the set of tags we support in titles to a few small ones (emphasis, bold, fixed-case, sup, latex-equation), potentially expanding this here or there as the situations require, or otherwise just rendering them to plain text.

If we go this way, the TODO item then is to extend our library calls for the following to be aware of the new structured format:

- bib to XML
- XML to MODS XML (which won't support all of these sub tags)
- XML to bib

**Comment by davidweichiang** [comment]
FWIW, before this conversation got going, I wrote a Python 3 script to convert XML+TeX to XML+Unicode. It uses the xml.etree module, so is likely to be more robust than anthologize.pl. It converts $...$ to <tex-math>...</tex-math>, but doesn't yet convert {...} to <fixed-case>...</fixed-case> or \emph{...} etc. to <i>...</i>.

In addition to the three bullets above, don't you need one for Anthology XML to HTML, or is that done via MODS XML?

**Comment by mjpost** [comment]
Yes, you're right: but this will be done by an XML → YAML script, which is then fed into Hugo to populate HTML template pages. @mbollmann has [already written that](https://github.com/acl-org/acl-anthology/blob/0a89ebb6d0fbe517ff09aa66e103a3dc07be5aaf/bin/xml_to_yaml.py).

**Comment by mjpost** [comment]
I am updating [my comment above](https://github.com/acl-org/acl-anthology/issues/135#issuecomment-463031216) to reflect consensus view of the TODOs here.

**Comment by jtrmal** [comment]
I have started working on rewriting the ingest of the official xmls (as I have discussed with @mjpost )
There is not much done for now (trying to figure out what really needs to be done), but my work will be in https://github.com/jtrmal/acl-anthology/tree/cite_ingest

**Comment by mjpost** [comment]
Hi Yenda—thanks for jumping in! Can you elaborate on what you mean by ingest? (ingest into what format)? I couldn't quite tell from [your commit](https://github.com/jtrmal/acl-anthology/commit/3d1eb6ec081f7f967f61183b93e97353358730a1).

It will be worthwhile for you to sync up with @mbollmann. He is heading up the static rewrite. The current status is that he should have the project in a state more amenable to divvying out pieces in a week or so.

**Comment by jtrmal** [comment]
Oh, OK -- so my understanding from our discussion was that you need someone to convert the "reference" xml (from ./import) to be converted into the MODS ones + done it in some way that would address the issues the older thing has (bookname and I forgot what else). Maybe this has changed?

**Comment by jtrmal** [comment]
Hm, I just noticed it should be #121, not #135, I don't even know how I got here, sorry.
I will remove the comments to reduce the clutter.

**Comment by mbollmann** [comment]
**Re: the math rendering**

I played around a bit with the `<tex-math>` instances and was not quite satisfied with any solution I could find. Pandoc mostly worked ok, but still failed to transform some instances that (in my opinion) have a reasonable representation in HTML (mostly involving `\sqrt` and `\frac`). Also, the contents of `<tex-math>` are mostly so simple that I was tempted to find out if I couldn't just write my own converter for them.

[This is the result.](https://github.com/acl-org/acl-anthology/blob/static-rewrite/bin/anthology/texmath.py)

It takes care of subscripts/superscripts and converts math symbols to Unicode using [this handy lookup table](http://milde.users.sourceforge.net/LUCR/Math/). If it can't interpret something, it is always preserved as a literal expression in the output, along with a warning during YAML generation. If you can access the beta site, you can see examples of generated output in [C16-1261](https://acl.uber.space/papers/C/C16/C16-1261/) or [W17-1912](https://acl.uber.space/papers/W/W17/W17-1912).

Now, I'm not sure what your opinion is on the maintainability of a homebrew solution like this, and I'm totally willing to switch over to pandoc instead if you'd feel more comfortable with that. But I think it works pretty well and should be pretty robust. Opinions wanted. :)

**Comment by davidweichiang** [comment]
Did you look at tex4ht? Is that better or worse than pandoc? How about using pandoc to convert to MathML?

Can we fall back to MathJax instead of raw LaTeX?

**Comment by mbollmann** [comment]
* tex4ht falls back to generating images when it can't represent pure HTML, however it already does this for simple cases like `\frac{m}{n}`, which I believe can reasonably be represented as <sup>m</sup>&frasl;<sub>n</sub>.  Also, invoking it and parsing the resulting HTML for the formula is quite involved for the trivially simple formulas we need to process.  But yes, due to the image fallback I would actually prefer it to pandoc, I think.

* MathML is [not widely supported yet in browsers](https://caniuse.com/#feat=mathml) as far as I understand it, and therefore should always be combined with MathJax.

* We could fall back to MathJax, but I really feel it isn't necessary at this point. Since we're only dealing with math inside titles and abstracts, the expected complexity of formulas is really minimal. For reference, [here's the full list of `<tex-math>` formulas currently in the XML files](https://gist.github.com/mbollmann/52a7aa9f2392b6008d75bbb0f24f817a).

**Comment by davidweichiang** [comment]
Ouch, line 17. I had been thinking classifying dollar signs as math delimiters vs. currency symbols and thought surely no string would use a currency symbol *twice*? I am quickly learning that such assumptions are always wrong.

**Comment by knmnyn** [comment]
Hi all:

It's great to try to automate everything but perhaps it's also good to have
a human in the loop to check and correct some cases manually by hand.  It
may be better for the scripts to flag to STDERR any suspicious cases, and
handle the 90-99% of normal case work.  Just a thought -- of course, that
is what got the Anthology in the messy state that it was before
Matt's directorship.

- M

**Comment by davidweichiang** [comment]
I'm closing this since it was decided to move LaTeX->HTML to ACLPUB.
