### ISSUE TITLE
XML has misplaced HTML tags

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#136]
For example, in D09-1031, the BibTeX title is 

```
How well does active learning {\emph{actually}} work? {Time-based} evaluation of cost-reduction strategies for language documentation.
```

But the XML says

```
<title>How well does active learning <i>actually work? Time-based</i> evaluation of cost-reduction strategies for language documentation.</title>
```

Presumably there was a bad regexp somewhere.

**Comment by mjpost** [comment]
This raises the issue of what should be in the XML file. My inclination is to use it to hold raw BibTeX, since that is the citation format I care about the most. The other formats are generated from the MODS XML file, so we can strip it when converting to those formats. But I may be overlooking something.

(Note: for many of these, the original BibTex file can be found by appending ".bib" to the PDF url under aclweb.org/anthology, e.g., [http://aclweb.org/anthology/D09-1031.bib]. So we may be able to automate the correction of many of these.)

**Comment by mjpost** [comment]
Update: compare to the [new anthology exported version](https://aclanthology.info/papers/D09-1031/d09-1031.bib), where the error is worse (also in the [paper page](https://aclanthology.info/papers/D09-1031/d09-1031)).

**Comment by davidweichiang** [comment]
Do you know where the code is that converts the original BibTeX to XML?

**Comment by mjpost** [comment]
I believe it's [this script: tools/anthoBibs2xml.pl](https://github.com/acl-org/acl-anthology/blob/master/tools/anthoBibs2xml.pl).

**Comment by davidweichiang** [comment]
Hm, I don't see any mention of `\emph` there, or anything that looks like it tries to match curly braces.

Presumably there are two bugs: The misplaced `<i>` due to a bad regexp when converting from bib to xml, and the truncated title when converting from xml to html -- my guess is that an XML script is only grabbing the first segment of text from the title element and not recursing on child elements.

**Comment by mjpost** [comment]
There are other ways to produce the input, for example, [this repo](https://github.com/acl-org/easy2acl/) for folks using easy chair. I don't see `\emph` there, either, though.

**Comment by davidweichiang** [comment]
Found it: [acl-pub/.../db-to-html.pl](https://github.com/acl-org/acl-pub/blob/0b6028f41787e43ddd1acbb82dca7882def40afa/assets/files/create_book/bin/db-to-html.pl).

**Comment by knmnyn** [comment]
Hi all:

Matt is right that the script is the source of (most) of the past automated
conversion of the BibTeX sourced from START/Softconf to the Anthology.
That said the script does throw warnings when the output has braces in it
on STDERR, and in the past, I manually fixed many conversions that were
problematic.
I found that the operational problems with canonicalization were often
one-offs, and I couldn't find sufficient bandwidth on my time to fix the
script to deal with this and some of the other exceptional cases.
Hope that helps! -M

**Comment by danielgildea** [comment]
I believe main script used to produce xml files for the anthology is [anthologize.pl](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/create_book/bin/anthologize.pl).

It used to call db-to-html.pl, but I got rid of that call, in order to use utf8
in the anthology xml files, rather than html escape codes for accented characters.

The script currently throws away `\emph`, rather than converting it to `<i>`.

**Comment by davidweichiang** [comment]
I made issue https://github.com/acl-org/acl-pub/issues/12 about this. But I'm not sure what the best way to fix old abstracts is.

**Comment by davidweichiang** [comment]
How about the script that converts XML to HTML (and is truncating at least that one title)? Which script is that?

**Comment by mjpost** [comment]
Do you mean for generating pages [like this](
https://aclanthology.info/papers/D09-1031/d09-1031)? That's part of the Ruby on Rails workflow, which I don't have any familiarity with. The code lives under [/app](https://github.com/acl-org/acl-anthology/tree/master/app), so you could probably poke around and find it, or maybe @villalbamartin has a quick answer. It may be worth waiting until @mbollmann finishes the static rewrite, which will replace these routines.

**Comment by davidweichiang** [comment]
Can the original .bib files be added to the repository? That would be a lot easier than scraping them.

**Comment by mjpost** [comment]
Here's a tarball: https://www.dropbox.com/s/4i3rqsy12x637ho/anthology_bib.tgz?dl=0

**Comment by davidweichiang** [comment]
Thanks, I got anthologize.pl to work on it, but it seems like diffing it against the current XML would be too much. So #138 is my best effort at resolving this issue.

Given that anthologize.pl is never going to be perfect, would you consider embedding the original BibTeX as an extra field inside the authoritative XML?

**Comment by mjpost** [comment]
For the diff, what if we just injected re-imported titles into the the existing XML? I'm assuming the diffs were nasty because you regenerated the whole XML file and things didn't line up.

Re: embedding, do you mean the entire BibTeX entry? I like this idea from the perspective of completeness though it would really uglify the XML, which is currently pretty readable (and gets edited all the time). What do you think about adding the bibs into a parallel directory structure and adding a field with the original bib file path, for each item? Maybe ugliness shouldn't be a concern, but there's going to be a lot of escaping.

**Comment by mjpost** [comment]
@danielgildea, do you know if our aclpub repo regularly imported by Softconf? My impression is most folks are building using the START "Generate" button and not from the command line.

**Comment by davidweichiang** [comment]
I'd be worried about re-importing the titles (and abstracts) because maybe some of them have been edited, right? I tried diffing EMNLP 2018, and it does line up, but it's dominated by differences in curly quotes. Maybe after normalizing some of the most frequent differences, it would become practical to look at the diffs and spot any cases where information has been lost.

I'd be okay with any scheme for including the original BibTeX files. It just sounds to me like those files are on the verge of getting retired, but they seem still important.

**Comment by knmnyn** [comment]
I'd agree with @mjpost to not make the XML redundant but store those somewhere, in case reingestion is needed.  The BibTeX submitted/generated from Softconf may be a superset of what is made in the XML but the XML should be the authoritative source from which any surface realization can be created as the realization logic is changed or upgraded.  

This was the original rationale for the XML from what I understand, as BibTeX as a canonical form has too many syntactic complications to serve as a canonical format.

**Comment by mjpost** [comment]
Okay, I will ingest the original bib files.

Note that `anthologize.pl` produces the XML, but I think that this is often regenerated from the master bib file with `anthoBibs2xml.pl`, in the current ingest process.

**Comment by danielgildea** [comment]
> @danielgildea, do you know if our aclpub repo regularly imported by Softconf? My impression is most folks are building using the START "Generate" button and not from the command line.

It is not regularly imported by Softconf, and we will have to bug the pub chairs of the next conference to get them to use the latest version.
