### ISSUE TITLE
Include revision URLs in XML

### ISSUE THREAD

**Issue by mbollmann** [acl-org/acl-anthology#145]
Currently, paper URLs are included in the XML within `<url></url>` tags, but revision URLs are constructed within the website template, e.g.:

https://github.com/acl-org/acl-anthology/blob/7a24dfe734b21e0b7952b26f67b328685a7d3b73/app/views/papers/show.html.erb#L29

I think this is an unfortunate mixing of content and presentation, and would suggest to include these full URLs in the XML instead, maybe as an additional attribute field so as to cause minimal disruption to existing toolchains:

+ **Current:**

```xml
<revision id='2'>D15-1060v2</revision>
```

+ **Suggested:**

```xml
<revision id='2' url='http://aclweb.org/anthology/D15-1060v2'>D15-1060v2</revision>
```

**Comment by knmnyn** [comment]
This was done to allow indirection instead of pinning to a specific URL.
Unlike the actual publication URL, which is DOI anchored.

So I understand Marcel's concern but I believe that it is for good reason.

**Comment by mjpost** [comment]
Under our [slightly revised corrections policy](https://github.com/acl-org/acl-anthology/blob/master/app/views/static_pages/corrections.html.erb), the main URL is anchored, but gets updated with revisions. I see the point about allowing for indirection, but at the same time, the ability does not seem used much, since we have an established convention of storing the revisions parallel to the original file (appending v1, v2, etc). I see Marcel's concern about mixing content and presentation, and think there may be some value in making the URL explicit. If we change it, we'd have to change the URLs, but it may be helpful to go that route instead of relying on a buried indirection policy.

I am also thinking that it would be useful to record a short reason for the change. So we could have something like

```xml
<revision id='2'>
  <url>http://aclweb.org/anthology/D15-1060v2</url> <!--If we adopt the proposed explicit URL, otherwise infer value-->
  <explanation>Fixed typo in formula 4.</explanation>
</revision>
```

There are only 76 revisions recorded in the current Anthology, so making these changes isn't too much work.

**Comment by mbollmann** [comment]
Thanks for providing the reasoning, @knmnyn.

I should add that this actually affects more than just revisions; internal attachments are treated the same way, for example. `<attachment>D14-1040.Attachment.zip</attachment>` gets resolved to `http://anthology.aclweb.org/attachments/D/D14/D14-1040.Attachment.zip` during database creation (so in yet another part of the pipeline).

For the static rewrite, I'm deriving all these URLs in the Python script (#129) for now, so that this logic is in a single place. I'd leave it up to @mjpost to decide whether to directly include them in the XML or not, but in any case it would be an easy change in these scripts in the future.

**Comment by mjpost** [comment]
I don't have a strong opinion on this. I see the point about indirection, and as long as the logic is in a clear place, it should be easy to follow what's going on.

**Comment by mbollmann** [comment]
Another factor that I hadn't considered is that full mirroring of the Anthology (#28) would also affect paper and attachment URLs. In light of that, it might actually be beneficial to leave them underspecified. Also, the logic for deriving the full URLs *is* in a single, clear place now, so I think we're good leaving it at that.
