### ISSUE TITLE
Handle problem with single bibtex encoding

### ISSUE THREAD

**Issue by cfedermann** [acl-org/acl-anthology#16]
**S/N:** 17
**Priority:** Medium
**Title:** Handle problem with single bibtex encoding
**Proposer:** Mark Steedman

**Comment by knmnyn** [comment]
There is a weird effect if one tries to grab bibtex encodings from the
link associated with the papers in at least the most recent conference
web pages, and paste them into one's .bib file via emacs.

The anthology bibtex files include automatically-inserted tab
characters.  These confuse some versions of the emacs editor *when it
has the buffer in bibtex mode*, making it impossible to paste in the
new entry, and generating an error

In particular, this happens with the emacs editor for Apple
OSX, and OSX's cut-and-paste.   (I don't think the latter has anything
to do with it, but I include it in case it does.   I think the problem
lies with the bibtex mode of this emacs.)

This is a problem because the full bibliographic reference isn't
available anywhere else for the recent papers.

The tab characters aren't doing anything good and may cause problems
further down the line for LaTeX in any OS.

Is it possible to eliminate them from the generation of bibtex entries
in the anthology?

**Comment by mjpost** [comment]
We should remove the tabs here when we [generate BibTeX files directly from the XML](#122).

**Comment by mjpost** [comment]
This is fixed in the static rewrite.
