### ISSUE TITLE
Anthology gives 404 after name changes

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#1645]
#### Issue description
Following #1598, searching for authors with a name change now results in a 404 error if you try to click through to the author from the search results.

#### Steps to reproduce the issue

1. Search for an author who has had their name changed (like Miruna Clinciu).
2. Navigate to their page from the [search results](https://aclanthology.org/search/?q=clinciu).
3. You will get a 404 error for [the relevant page](https://aclanthology.org/people/m/miruna-adriana-clinciu/).

#### What's the expected result?
The expected result is to land on the author page. (Possibly redirected from their old author page.)

#### What's the actual result?
A 404 error.

#### Additional details / screenshot
I am not sure whether this is just a single error, or whether this holds for all authors who have had their name changed in the Anthology.

**Comment by akoehn** [comment]
The problem should go away with a reindex by google; as we use an external search engine, the results are not always in sync with the actual data.

We will not redirect everyone with a different name in the past because some names were just incorrect (spelling etc) and people might not want to be found with previous names.  In addition, we would need to add new logic for that.  Also, I don't think we made a promise to keep author URLs stable (although we try), so in my opinion the current state is okay.

**Comment by evanmiltenburg** [comment]
Thanks Arne! I agree that if this is resolved by Google reindexing the Anthology, then it's fine. Stability is nice to have, but I also understand it takes quite a bit of work.

**Comment by akoehn** [comment]
Thanks for reporting!  We can only look at things we know of.
