### ISSUE TITLE
Create SyntaxFest as an event

### ISSUE THREAD

**Issue by texttheater** [acl-org/acl-anthology#1774]
As discussed previously with Matt via email, it would be nice to create SyntaxFest as an event in the Anthology. It would contain the following venues:

### 2019

* https://aclanthology.org/volumes/W19-80/
* https://aclanthology.org/volumes/W19-79/
* https://aclanthology.org/volumes/W19-78/
* https://aclanthology.org/volumes/W19-77/

### 2021

* https://aclanthology.org/volumes/2021.udw-1/
* https://aclanthology.org/volumes/2021.tlt-1/
* https://aclanthology.org/volumes/2021.quasy-1/
* https://aclanthology.org/volumes/2021.depling-1/

**Comment by mjpost** [comment]
It was created as a venue in #1738: https://aclanthology.org/venues/syntaxfest/

This means there are two corresponding events: [2019](https://aclanthology.org/events/syntaxfest-2019/) [2021](https://aclanthology.org/events/syntaxfest-2021/)

What you asked for above are volumes, but since SyntaxFest issues no proceedings, it will not have volume pages.

**Comment by mjpost** [comment]
We weren’t sure what to call it, and settled on “Joint Meeting of Four Workshops on Syntax”. If you have another suggestion, please create a PR (the edit goes in `data/yaml/venues.yaml`).
