### ISSUE TITLE
garbled 2021.paclic.xml

### ISSUE THREAD

**Issue by danielgildea** [acl-org/acl-anthology#1821]
Something seems to be wrong with 2021.paclic.xml. The list of papers does not correspond to the table of contents in the volume pdf. For example, the first paper in the pdf, "Under the Microscope: Interpreting Readability Assessment Models for Filipino" doesn't appear in the xml file.

**Comment by xinru1414** [comment]
@danielgildea Thank you for raising this issue again (see comments #1783). I've been in contact with the person in charge. They explained that since it has been holiday season in China (spring festival, lantern festival), things have been moving slow. I'm still waiting on the new proceedings to reingest.

**Comment by ridho-kata** [comment]
Hi, I'm not sure if this is related but today when I went to check the papers of 2021 PACLIC the pdfs are all incorrect.

https://aclanthology.org/events/paclic-2021/ 

For example, if I go to the first paper "A MARVS Analysis of Two Chinese Near-Synonymous Verbs of Jumping Based on Chinese Corpora" and try to download it, I get the pdf of "Under the Microscope: Interpreting Readability Assessment Models for Filipino"

I have checked  3 other papers and they have the same problem.

**Comment by mjpost** [comment]
@xinru1414 has the updated proceedings from the PACLIC organizers and will have this updated soon.

**Comment by xinru1414** [comment]
@ridho-kata this should be fixed now
