### ISSUE TITLE
Broken links despite presence of files

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#1828]
The links at https://aclanthology.org/posts/ produce 404s when clicked, despite [the presence of the files in that directory](https://github.com/acl-org/acl-anthology/tree/master/hugo/content/posts). Is there a quick fix for this?

(What I'd really like under posts/ is a blog (#722).)

**Comment by mbollmann** [comment]
Huh. Might be because there's no page template. There is no `hugo/layouts/posts/single.html`, and there's also no `single.html` template under `hugo/layouts/_default/`.

You could try creating a new layout e.g. by copying the layout from the info pages, or add `type: info` in the frontmatter of the posts to tell Hugo to re-use the "info" template.
