### ISSUE TITLE
Mismatch between webpage URL and PDF URL

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#1831]
I thought that the webpage URL was supposed to be identical to the PDF URL minus the extension, but here is a counterexample:

https://aclanthology.org/2021.ranlp-1.156/
https://aclanthology.org/2021.ranlp-main.156.pdf

https://aclanthology.org/2021.ranlp-main.156 gives a 404.

**Comment by mjpost** [comment]
Yes, there is a mistake here. Either the volume should be named "main" in the XML, or the paper IDs should have used "1" instead.

This is an unfortunate error because it is either going to break people's PDF links or page links. The canonical pages, however, are given by the non-PDF url. Since https://aclanthology.org/2021.ranlp-1.156 exists, but not https://aclanthology.org/2021.ranlp-main.156, I suggest we rename the PDFs, as well as the `<url>` tags in the XML. This will consolidate everything on the volume name of "1" instead of "main".

@xinru1414 can you add this to February's corrections?

**Comment by xinru1414** [comment]
@mjpost renamed the PDFs on the server
