### ISSUE TITLE
Bug report-different statistics of papers from website

### ISSUE THREAD

**Issue by qolina** [acl-org/acl-anthology#2034]
#### Issue description
Hi, we are a team who want to contribute to ACL anthology by extracting text from pdf files and further apply SOTA NLP toolkits on the extracted text.  

When I use `make mirror` to download pdf files from the latest ACL anthology corpus on July 6th. Yield 72889 files under `./build/anthology-files/pdf/` on 8th. While the https://aclanthology.org/ website says 

> The ACL Anthology currently hosts 76XXX papers on the study of computational linguistics and natural language processing.

sorry forget the exact number as it is updated to 77762 files today.

#### What's the expected result?

Same number with the website.

#### What's the actual result?

A few thousands lower than expected.

#### Additional details / screenshot

I use the `find ./ -name *.pdf > filelist.txt` command to  retrieve all pdf files under the `./build/anthology-files/pdf/` 

A second trial on July 12th yield 74234 files with a full log file indicating we only have 1 paper failed to download.

**Comment by mbollmann** [comment]
Is your local copy of the repository up-to-date, i.e. have you `git pull`ed the latest changes?

There should be 76974 main paper PDFs (i.e., disregarding errata/revisions/attachments) according to my calculations:

```python
>>> from anthology import Anthology
>>> ant = Anthology("../data")
>>> pdfs = [paper.pdf for paper in ant.papers.values() if paper.pdf is not None]
>>> len(pdfs)
76974
```

(This number is lower than the total number of papers because a couple of hundred papers are listed, but do not have any PDF file.)

**Comment by qolina** [comment]
Thanks @mbollmann. Previously, I didn't count as you suggested, but counted 72889 pdf files under `./build/anthology-files/pdf/`. I just tried your way today, it returns that 75650 papers (old version so less than your 76974) have pdf files, much larger than the stored pdf files in `./build/anthology-files/pdf/`. It makes me more curious about where other pdf files are? Do you have any clues?

**Comment by mbollmann** [comment]
One thing to note is that we have some proceedings that we index, but that are actually hosted externally, e.g. [LREC 2014](https://aclanthology.org/volumes/L14-1/). It would make sense if the mirroring script did _not_ download them, since they're not hosted by us. But I'm just guessing here, @akoehn wrote the script so he should know best. :)

There are also a few instances of papers that are listed without any PDF, like [this one from ACL 1979](https://aclanthology.org/P79-1024/). I think these will currently count towards the statistic on the front page, but of course mean that the number of downloaded PDFs won't exactly add up.

Either way, in principle you could use my code snippet above to get all the paper PDF URLs, so you could use those to download all the PDFs too. I also [made a script to download papers based on their IDs](https://github.com/coastalcph/acl-citations/blob/master/bin/acl_anthology.py), maybe this could be useful for you too.

**Comment by akoehn** [comment]
Yes, the script should only be downloading pdfs that are hosted "locally". The easiest way forward would be to use an xpath query to get the pdfs that are supposed to be downloaded and diff that list with what's actually there (but the downloader is already doing that and when called again, it should only process the missing pdfs and the ones not matching the hash) 

I can have a look at that tomorrow.

**Comment by akoehn** [comment]
The number on the index of the anthology website calculates the number of papers in the "database", whereas the number of papers actually *hosted* on our servers is a (very big) subset of that.  As @mbollmann wrote, LREC is an example for externally hosted papers; non-archival papers are a second group where we have metadata but no PDF.

In the XML, the difference is easiest to be seen by the (non-) existence of a hash value for urls (we only have hashes for local files):

```
$ grep '<url hash' *xml | wc -l
73656
l$ grep '<url' *xml | wc -l
78515
```

(the 78515 is not a relevant number; there are also other URL tags, but you can get some relevant examples of papers with a PDF linked externally by going through the output of `diff -u <(grep '<url' *xml | sort) <( grep '<url hash' *xml | sort)`.

The additional ~600 PDFs might be revisions of papers; I have not counted the exact number for these, but I don't think it is an error in the mirroring logic; the mirroring script simply directly queries the XML files using xpath.

**Comment by qolina** [comment]
Thanks, @mbollmann and @akoehn. I think your suggestions help us a lot with the downloading issue.
