### ISSUE TITLE
Correction to Anthology ID 2022.ccl-1.73

### ISSUE THREAD

**Issue by zsquaredz** [acl-org/acl-anthology#2193]
## Option 1: Metadata correction

The order of first-name and surname of both authors in the paper is displayed wrongly in the metadata. It should be "Zheng Zhao"  (first-name=Zheng, surname=Zhao) and "Pinzhen Chen" (first-name=Pinzhen, surname=Chen) instead of the current "Zhao Zheng" and "Chen Pinzhen". I found this seems to be a common problem for most English paper in CCL. Perhaps there is an error in the processing script for this conference as Chinese name typically has the order of surname+first-name instead of the typical first-name+surname. When processing the Chinese names, the scripts can easily get the wrong order.  

Accordingly, the <bibkey> should be "zhao-chen-2022-adapt" instead of "zheng-pinzhen-2022-adapt".

**Comment by xinru1414** [comment]
@zsquaredz Thank you for pointing this out. However, the order of first name and last name for both authors is wrong in anthology metadata is because the order is wrong in the bib file ( see screenshot below):

<img width="443" alt="Screen Shot 2022-10-13 at 10 13 58 PM" src="https://user-images.githubusercontent.com/27436920/195767434-1a6235b2-10ef-4aa3-b823-895241418b79.png">

The author field should be `last name, first name` for each author, i.e. the author filed of the bib file for this paper SHOULD look like this:

`Zhao, Zheng and Chen, Pinzhen`

**Comment by zsquaredz** [comment]
@xinru1414 Thank you for your help! So will you help us to correct this? Or if I need to modify this myself, could you please let me know where I can modify this bib file?

**Comment by xinru1414** [comment]
@zsquaredz I will!

**Comment by zsquaredz** [comment]
@xinru1414 Thank you! Also, just curious why is your screenshot of bib is different from the one on here: https://aclanthology.org/volumes/2022.ccl-1.bib ? Also the bibkey in yours has the year of 2021 which is also quite strange, shouldn’t it be zhao-chen-2022-adapt?

**Comment by xinru1414** [comment]
@zsquaredz  Not sure what you mean:

1. bib from https://aclanthology.org/volumes/2022.ccl-1.bib of the paper (notice the author order):
<img width="659" alt="Screen Shot 2022-10-13 at 11 03 36 PM" src="https://user-images.githubusercontent.com/27436920/195773792-eb05366b-ff83-428c-b968-292a3e23872e.png">

2. bibkey (2022) 
<img width="807" alt="Screen Shot 2022-10-13 at 11 05 54 PM" src="https://user-images.githubusercontent.com/27436920/195774107-11e3cd5c-ff87-4fc3-83bf-d751689c63d1.png">

**Comment by PinzhenChen** [comment]
I found that the data in https://github.com/acl-org/acl-anthology/blob/master/data/xml/2022.ccl.xml are not consistent. For Chinese papers the firstname and lastname seem correct but these fields seem swapped for *all* Chinese papers.

I not not sure if the bib file generates this, or it’s the other way round.

**Comment by zsquaredz** [comment]
> @zsquaredz Not sure what you mean:
> 
> 1. bib from https://aclanthology.org/volumes/2022.ccl-1.bib of the paper (notice the author order):
> 
> <img alt="Screen Shot 2022-10-13 at 11 03 36 PM" width="659" src="https://user-images.githubusercontent.com/27436920/195773792-eb05366b-ff83-428c-b968-292a3e23872e.png">
> 
> 2. bibkey (2022)
> 
> <img alt="Screen Shot 2022-10-13 at 11 05 54 PM" width="807" src="https://user-images.githubusercontent.com/27436920/195774107-11e3cd5c-ff87-4fc3-83bf-d751689c63d1.png">

@xinru1414 In [this](https://github.com/acl-org/acl-anthology/issues/2193#issuecomment-1278497462) comment, you uploaded [this](https://user-images.githubusercontent.com/27436920/195767434-1a6235b2-10ef-4aa3-b823-895241418b79.png) screenshot which has the bibkey as "zheng-etal-2021-to". It seems strange as it is different from the bibkey entry now on the website, and I was not sure where this is coming from.

**Comment by xinru1414** [comment]
@zsquaredz oh i see what you mean. So the first entry in the `inproceedings` is called a `citekey` I believe. We refer to bibkey as in the screenshot I shared above `zheng-pinzhen-2022-adapt` (that's why I was a bit confused). 

We receive bib files (as part of ingestion material) from conference organizers, which I believe are submitted from the authors? 

@PinzhenChen Could you be more specific? What do you mean by `fields seem swapped for all English papers.`?

**Comment by PinzhenChen** [comment]
Hi @xinru1414, I mean for most if not all Chinese papers, the "first name" field in the XML file has the value of a last name; the last name field usually is a first name. We find this to be a consistent error in the XML file. It might be a result of a mismatching data interface/generator.

also ref #2181

**Comment by mjpost** [comment]
A few points of clarification:

* If the names are reversed, it's because that's how the data was given to us by the CCL organizers. Our ingestion routines are automatic. In the _incoming_ bibfiles, they names should be listed in BibTeX format, e.g., "Matt Post and Xinru Yan" or, preferably, "Post, Matt and Yan, Xinru".
* We are happy to resolve these issues. We could re-ingest, if the CCL organizers fix the data. Alternately, someone could edit `data/xml/2022.ccl.xml` to resolve the problem, submit a PR, and we can accept that.
* The `<bibkey>` field in the XML is used to set the citation key in the exported bibfile. So those fields should also be updated.
* Please note that Anthology bibles (such as https://aclanthology.org/volumes/2022.ccl-1.bib) are _generated_ by us from our underlying XML. Those files will be fixed when the underlying data is fixed.
