### ISSUE TITLE
Correction to Anthology ID 2022.inlg-main

### ISSUE THREAD

**Issue by ThiagoCF05** [acl-org/acl-anthology#2324]
## Option 1: Metadata correction

*Submission number 37, accepted as an oral presentation, was not imported from OpenReview, then not added to the proceedings. *

## Option 2: Revision or erratum

- [ X] I have attached the revised PDF or erratum to this issue
- [ X] I have written a brief description of the changes below

The link to the new proceedings containing submission number 37:

https://drive.google.com/file/d/1kiDThU0EN2C4vzVSz7gfGl19AXDvXdEo/view?usp=sharing

**Comment by xinru1414** [comment]
@ThiagoCF05 Is the paper itself ingested to the anthology? If so what is its anthology ID?

**Comment by ThiagoCF05** [comment]
Dear @xinru1414 ,

Thanks for the quick response. 

It was not ingested by the anthology. Current proceedings do not have paper number 37.

Best,

**Comment by xinru1414** [comment]
@ThiagoCF05 In that case, paper 37 can only be ingested as the last paper: https://aclanthology.org/volumes/2022.inlg-main/ i.e. following paper https://aclanthology.org/2022.inlg-main.24/. This is due to anthology IDs can not be changed for the existing papers, which means paper 37 will have anthology ID `2022.inlg-main.25`.

Please 1. double check that the main proceedings.pdf has paper 37 as the last paper, and 2. submit the pdf for paper 37 itself.

**Comment by ThiagoCF05** [comment]
Dear @xinru1414,

Once again, thank you for your help. I added the paper at last in the proceedings. Here it is the links:

Proceedings: https://drive.google.com/file/d/1cKdJv_9Zg478WvKXy3DVjU0QrVCwEqrP/view?usp=sharing
Paper: https://drive.google.com/file/d/1bXdq7bjkeVnyE_0xOwXeW8eTjqJETCdn/view?usp=sharing

Thanks in advance,

**Comment by ThiagoCF05** [comment]
Dear @xinru1414 ,

Is there an update on the issue?

**Comment by ThiagoCF05** [comment]
Dear @xinru1414 ,

Do we have any update on this issue?

Thanks in advance,
Best.
