### ISSUE TITLE
Make previews more recognizable as such

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#2356]
We should add a very clear watermark on Anthology previews to prevent this kind of mistake. 

@cdmalon this pr is still marked as a draft and, to quote @xinru1414:
> We are, in fact, still waiting on certain EMNLP material to be delivered

It seems like a lot of people are visiting the preview rendering (judging from logs). To be very clear: this is not a published version, the preview is only an internal tool to check whether a pull request works as intended. Please do not view this as "the emnlp proceedings". If you want to know when the proceedings are published: watch this PR and wait for the merge notification. Only then will the proceedings be published. (Or wait for an announcement on other channels)

_Originally posted by @akoehn in https://github.com/acl-org/acl-anthology/pull/2283#issuecomment-1409025903_

**Comment by akoehn** [comment]
Yes, I thought about how to do that in the past, I think a popup would be good. I actually have 10 minutes right now and will see whether there is a quick solution.

**Comment by akoehn** [comment]
"this is an *internal preview* and not the official acl anthology! Do not treat this content as an official publication and don't report missing data unless you know what you are doing"

Or what else should we show?

**Comment by akoehn** [comment]
Like this, either injected into the html during rendering (might add complexity) or do it the dirty way and inject it via js if the domain starts with preview:

![image](https://user-images.githubusercontent.com/220577/215566583-19310377-1b77-485a-8876-1d34d9a1fa3c.png)

Unfortunately, I cannot render the anthology on my work computer because the anti-virus checks every file being touched, leading to a ~50x slowdown :-/

**Comment by cdmalon** [comment]
The preview proceedings were linked to during the conference by Underline and we are extremely grateful that they publicized this resource.  Without them, we would have had no idea of the technical details behind any of the talks and posters we saw and heard.

Yes, we know this is only a preview, but we need as much as we can get, now.  Already the next set of conference deadlines is approaching (for most ACL 2023 tracks, it even passed) and there is no way to conduct research that builds on the current generation of research results without getting access to these papers.  Many people are satisfying their needs with the preview, but my paper is one of the unlucky ones, and publishing in EMNLP this year turned out to be a great way to ensure my work had zero impact on the field.

I would suggest you close this ticket and concentrate on finishing #2283, and please give incremental updates to the preview as often as you are able.

**Comment by mbollmann** [comment]
@cdmalon The delay is **not** in the hands of the ACL Anthology volunteers that you're talking to here. It is entirely in the hands of the publication chairs of EMNLP 2022. These are the people you should address this to.

**Comment by mbollmann** [comment]
@mjpost Many people are visiting the preview branch because its link prominently features in the main menu of the [EMNLP 2022 website](https://2022.emnlp.org/) under the heading "Proceedings". I find this pretty outrageous tbh, because it effectively makes it look like it's the Anthology's fault now if something there doesn't look as expected for a published proceedings volume.

We should absolutely do something to discourage this kind of behaviour.

**Comment by akoehn** [comment]
One thing we could do is make the previews password protected with .htaccess. I actually think this is better than a banner.

The password can be in our readme or whatever, but that would 1) keep the integrity of the preview files 2) prevent indexing by search engines and 3) the password prompt could contain the relevant text (you are entering a preview environment etc pp)

@cdmalon I understand your frustration, but as @mbollmann said, this is not the place for it. You can only see anything at all because we already do everything in the open and people can follow changes.

**Comment by akoehn** [comment]
Oh, and absolutely agree with @mbollmann re their links (and underline), did they ask?

**Comment by mjpost** [comment]
@cdmalon I wish this were under our control, because then it would have been done. We have been in long discussions with the EMNLP organizers, but at the same time, it is not our job to babysit them. Every other *ACL conference delivers its proceedings a week or two ahead of time and we process them promptly.

@akoehn That banner looks great. Do you have code for it? I can fiddle with the message if there is a quick fix. I think it's also crucial that this banner gets added to every page, since there are a lot of incoming links.

**Comment by mjpost** [comment]
Also, I really thought we had disallowed indexing. I just created a root-level `robots.txt` on https://preview.aclanthology.org/.
