### ISSUE TITLE
Authors with only one name

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#237]
PR #233 tries adding a name variant with only a last name and there are some technical issues there, but there is also the more basic issue of:

- Should the XML distinguish between an author with only a first name vs. an author with only a last name? I'm unsure whether this is a real distinction. 
* Only first name: Chandrahas.
* Only last name: Abhimanue, Budiono, Govind, Mausam, Odbal, Shweta, Srinivas, Sukhada, Toni.
* Neither: Yes, there are several in ROCLING; presumably these should be deleted.

- What about corporate authors like:
* ARC A3
* Annotation Group
* Architecture Committee
* European Association for Machine Translation (maybe shouldn't be an author anyway)
* Forschungsgruppe LIMAS
* PLUM Group
* SRA International
* TIPSTER SE

**Comment by mbollmann** [comment]
I think we should look at this from a functional perspective — we don't need to represent the precise semantics of names in all possible constellations, but rather introduce distinctions only if they result in a functional difference for (some part of) the website.

The only real significance of the first/last name distinction at the moment is, I believe, the BibTeX export. There's the highlighting of last names on author pages, but that mainly serves to make name variants clearer. For both of these, I feel it's adequate to represent corporate authors as `<last>corporate name</last>`. The same could be done for first-name-only authors, as even though it's not quite semantically correct, I can't foresee a functional difference at the moment (but, on the other hand, a lot of complications if we allow first-name-only).

That said, there's two things that need to be fixed in my code:

1. The BibTeX export needs to omit the comma for last-name-only.
2. Corporate names should be wrapped in extra curly braces to prevent BibTeX from trying to parse them into first/last names. I think here it would suffice and produce correct results to simply add these curly braces for all last-name-only authors.

**Comment by davidweichiang** [comment]
I think I agree. What we call `<last>` is basically just "the part of the name that we cite and sort."
