### ISSUE TITLE
TLT

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#2419]
Pre-2020 years of TLT need to add the [`tlt` venue](https://aclanthology.org/venues/tlt/), e.g.

https://aclanthology.org/volumes/W17-76/

It's possible not all proceedings are in the Anthology. https://dblp.org/db/conf/tlt/index.html lists the earliest one as 2002.

**Comment by xinru1414** [comment]
@mjpost It seems like old-style workshops all have `ws` as their `<venue>` tag. How do we want to handle these?

**Comment by mjpost** [comment]
Yes, all workshops pre-2020 were just labeled as WS because we don't know their real venue when we made venues explicit, and because there were no venue labels for everything when they were originally assigned. As we discover them we should switch the tag value. Ideally someone from each venue would go through and identify them.  I've done this for WMT for example.

**Comment by xinru1414** [comment]
W17-76 is the only one I could find that isn't associated with tlt. Other tlt volumes either already has the `tlt` venue tag or the `SyntaxFest` venue tag.
