### ISSUE TITLE
How to annotate first initials in XML

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#245]
@mjpost and I have been discussing offline: When an author's name is written using a first initial on the paper itself, but the complete first name is known (at least probably), how should it be written in the XML? Some ideas (others are possible):

```
a) <author><first>Matt</first><last>Post</last></author>
b) <author><first>M[att]</first><last>Post</last></author>
c) <author><first complete="Matt">M.</first><last>Post</last></author>
d) <author><first initials="M.">Matt</first><last>Post</last></author>
e) <author><first>M<completion>att</completion></first><last>Post</last></author>
```

We have a big influx of these, thanks to the hard work of the LREC organizers supplying complete first names, so if the answer is anything other than (a), it would be nice to decide before merging in the new ones.

JATS uses (d) but without the period (https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-zu82.html).

Some special cases to consider:

- Initials are not always initials: `Wm.` to `William`, `R.` to `Bob`
- Middle initials, double first names, second last names, etc. can be expanded from initials as well.
- ADDED: Possibly related, possibly a can of worms: There are some (but not many) papers where the author's name is written _only_ in a non-Latin script (e.g., https://www.aclweb.org/anthology/O00-1008), so the editor has filled in a transliteration.

**Comment by mbollmann** [comment]
I'm not sure I would want to make a functional difference here between this and any other name variants. The only robust way to clearly identify an author is via some kind of ID. Everything else will only lead to more problems in the future, IMHO.

**Comment by davidweichiang** [comment]
The difference between this and other name variants is that the chance of collisions is much higher. So you're right that the name collision problem (#208) is the real issue that needs to be resolved.

I think what makes this tricky is that, abstracting away from any questions like "what is a first/last name?" and focusing on functionality (as decided in #237), the author entries in the XML still serve three purposes:
- Identify an author (by matching an entry in `name_variants.yaml`)
- Generate names for the website and BibTeX
- Record what the authors wrote on the original paper
And these three purposes are not always aligned.

**Comment by davidweichiang** [comment]
Will it be okay with @mbollmann @mjpost if I go ahead with option (d) for now? This would require only a minor change to the schema, no modifications to code, and it would be easy to convert to another style. It also conforms with an established standard ([JATS](https://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/initials.html)) and is consistent with [CMoS style](https://www-chicagomanualofstyle-org.proxy.library.nd.edu/book/ed17/part3/ch14/psec073.html), which I believe ACL's style is most similar to. (I also believe that even with a good solution for name collision, this is still the best option.)

**Comment by mjpost** [comment]
This is good for the name collision, but it also means we are overriding author preference as to how their name is displayed, correct? This is in line with JATS policy, but my preference is to gather names under the canonical form that is evidenced by majority vote across the representations an author chose for their papers (i.e., (c)). 

What is your reason for preferring (d) over (c)?

**Comment by davidweichiang** [comment]
What I gather from manuals like CMoS is that there's a distinction between whether an author prefers to use initials (e.g., C.S. Lewis), vs. when initials are an abbreviation of the author's preferred spelling (e.g., because the conference requires it, or there wasn't enough space in the titlebox, or the lead author wanted to, or whatever). In the former case, initials shouldn't be expanded, but in the latter case, they can be.

So the rule of thumb would be something like: if an author name uses an initial, and the initial is expanded in a majority of the author's other papers, then expand the initial.

**Comment by mjpost** [comment]
I agree with this logic but don't see the connection to the (c) versus (d) decision. My view is that element values should reflect the PDF (which is the closest thing we have to author preference) and attribute values should be used for disambiguation; this also fits @mbollmann's view of using using IDs to resolve collisions (since these would be attributes). But I think we have heard each other out, and you are closer to the trenches here, so please proceed as you see fit.

**Comment by davidweichiang** [comment]
I think (c) is fine too. And I see now that it makes good sense to use the `complete` attribute and an eventual `id` attribute together to resolve collisions. Do we want the `complete` names to appear on the website and BibTeX (my opinion: yes)? If so, there will have to be additional logic to substitute them in, whereas with (d), it will happen for free.

**Comment by mjpost** [comment]
I think we should separate out completely the issues of correctness, disambiguation, and display:

- correctness means that for each paper, we have a record of the exact name that was printed on the PDF, subject to correction of typographical errors
- disambiguation means that some of those authors may need to have additional attributes that assign the paper to the correct cluster
- display denotes the set of names that are displayed with each cluster

From the (c) view:
- correctness is captured by the contents of the `<first>` and `<last>` tags
- disambiguation is handled by using attributes to assign each author instance (token) to the correct author cluster
- display for an author cluster is handled by (i) collecting all the author token instances, which make up the set of "published as" tokens and (ii) adding to this information (IPA, foreign script renderings, complete names found in `name_variants.yaml`. (i) here is accomplished easily by collecting the values of all `<first>` and `<last>` name tags across the paper's in the author's cluster.

So to answer your question, in (c), we *would* use the `complete` names. They could come either from the attribute tags on paper instances, or they could be gathered and entered into `name_variants.yaml` in offline processing. This latter approach seems easier to me.

If we used (d), yes, we would get this for free, but then recovering the "correctness" issue would require some logic instead of just reading the values from `<first>` and `<last>`.

**Comment by davidweichiang** [comment]
Display also pertains to how individual papers ('tokens') are displayed on the website and in BibTeX, right? Not just the author pages ('types')? In other words, would a paper whose XML has `<author><first complete="Matt">M.</first><last>Post</last></author>` have a BibTeX entry with `author = "Matt Post"`?

I think you've convinced me to go with (c), not on the basis of code complexity (because I feel it would be the same either way, just in different places), but because it makes sense to use attributes for two levels of disambiguation, rather than one attribute (`id`) for disambiguation and one attribute (`initials` or `original`) for "ambiguation".

I can go ahead and merge in the first names from LREC as a `complete` attribute, but there will be no immediate visible effect on the website.
