### ISSUE TITLE
Changes required for indexing of Workshop Papers (ACL Anthology)

### ISSUE THREAD

**Issue by asdogruoz** [acl-org/acl-anthology#2706]
Currently, each ACL workshop (listed in ACL Anthology) stands as a volume of its own. The workshop organizers act as editors of this volume in the front matter. However, the organizers are not listed as editors of the workshop papers in the Bibtex (ACL). This is a request to include the editors of the workshops in the Bibtex referencing of the ACL Workshop papers which will improve scientific indexing of these papers and recognize the workshop editors' efforts who organize the whole event and prepare the papers for publication.

**Comment by mbollmann** [comment]
I can totally see the reasoning behind this. Two purely technical notes:
1. The ACL natbib style [will not currently render the "editor" field for `@inproceedings` entries](https://github.com/acl-org/acl-style-files/blob/master/latex/acl_natbib.bst), and it looks like this was a conscious decision at some point, though I don't know why:
 https://github.com/acl-org/acl-style-files/blob/3a7a4d1d1c4e153dd8edb9411aa6dc0a45444bce/latex/acl_natbib.bst#L121-L124C14
2. If we implemented this, we should probably make sure that the individual workshop papers do not appear on the author pages of the workshop editors.

**Comment by nschneid** [comment]
> 1. The ACL natbib style [will not currently render the "editor" field for `@inproceedings` entries](https://github.com/acl-org/acl-style-files/blob/master/latex/acl_natbib.bst), and it looks like this was a conscious decision at some point, though I don't know why:

Proceedings entries in the bibliography using Anthology BibTeX are fairly long even without showing program chairs/workshop chairs as editors. Personally I'd be happy if it stayed that way in the stylesheet. But I have no objection to including the editors in the BibTeX.

LREC-produced BibTeX used to do this BTW ([example](http://www.lrec-conf.org/proceedings/lrec2018/summaries/391.html)), but starting with LREC 2020 it seems they stopped including the `editor` field on papers.

> 2\. If we implemented this, we should probably make sure that the individual workshop papers do not appear on the author pages of the workshop editors.

To state this is more general terms: Anthology author pages would need to recognize the editor role as something that applies to an entire volume but not the individual papers in that volume (for purposes of listing all the publications from that individual).

**Comment by knmnyn** [comment]
I think Seza's idea makes sense and it seems it would be pretty easy to check how well propagating author information from volume frontmatters would correctly populate editorships.  I recall that in the earlier part of the Anthology's materials there are volume where frontmatter was not attributed to any author.  I guess we would only propagate in one direction (frontmatter to volume) and not the other way around.

**Comment by asdogruoz** [comment]
Thank you for the comments and suggestions. I have encountered yet another indexing issue this week about the workshop papers since they lack an editor. It will be great if we are able to solve this issue soon before things get more complicated. 

1) APA style could serve as a guide for referencing: https://apastyle.apa.org/style-grammar-guidelines/references/examples/edited-book-chapter-references
2) ACL'2023 workshops are also lacking DOI numbers now. 

What would be the timeline to resolve these issues? Who could help to try a few things to find the best solution?

**Comment by mbollmann** [comment]
I'm all for fixing this if it is a problem and no one has any objections, but how come there is an urgency now when this has been the status quo for all past workshops for many years?

1. When we introduced pre-formatted references, we decided against having APA, but use the official ACL style instead. This could be changed of course, but then again I don't think which citation style is used in the Anthology has any bearings on the indexing.
2. DOIs are added in #2723.

For reference, this one line of code prevents the propagation of volume editors to the individual paper entries:
https://github.com/acl-org/acl-anthology/blob/8358952444c6bedb0788aa4ec14ca0b4c505da56/bin/anthology/papers.py#L52-L54

Removing this condition might already do what we want, but might also break things since papers are allowed to have their own `<editor>` tag as per the schema. We'd have to carefully test this change.

**Comment by mbollmann** [comment]
@asdogruoz #2798 adds editors to the BibTeX; some examples from the preview:

- https://preview.aclanthology.org/propagate-editor-field/2023.americasnlp-1.2/
- https://preview.aclanthology.org/propagate-editor-field/2023.repl4nlp-1.1/
- https://preview.aclanthology.org/propagate-editor-field/2023.acl-long.1/ (also affects conference proceedings)

I wonder if and how we should show the editor field in the pre-formatted citation string (where it says "**Cite (ACL)**"), because it looks quite verbose now. Maybe it would be sufficient to have the full editor list in the BibTeX, but render the pre-formatted citation with "{Editor1} et al."?

**Comment by nschneid** [comment]
Thanks @mbollmann! A couple things that popped out to me:

- Cite (Informal) should have the author name, not the editor name
- Agree re: verbosity
- Right now the vertical alignment of "Bibkey:" and "Cite (ACL):" is not quite right. I assume this is just because the .bib file is not generated in the preview, so the bibkey is missing?

**Comment by mjpost** [comment]
Thanks for this preview, Marcel! This adds quite a bit of verbosity to the citation preview, particularly for [workshops with long lists of organizers](https://preview.aclanthology.org/propagate-editor-field/2022.wmt-1.1/). I wonder if we need to add some documentation for this, for people alarmed by the change? One suggestion is a little info hover-over icon with (i) or (?) that would explain the change; we could note that the citation includes the volume editor field, but that the BST file need not use this field (and that ACL's doesn't).

Maybe not necessary but I am trying to anticipate community reaction.

**Comment by mbollmann** [comment]
Technically the "Cite (ACL)" field is supposed to mimic the ACL BST, so if it doesn't here, that's a bug in the CSL file (which we use to generate this).

(On an only slightly related note, the build check in #2798 has now failed three times in a row presumably due to memory/resource issues ... I fear this is starting to become a more serious issue as the Anthology grows)

**Comment by asdogruoz** [comment]
Thank you, all. Is there an update on this?

**Comment by mbollmann** [comment]
Yes, I've rebuilt the PR #2798 now that we have fixed the build issues, so technically this can be merged.

I don't see a consensus here on what we should do about the verbosity of the citations on the paper pages. I assume the important change is the BibTeX, not the example citation on the website (which, either way, is a very recent addition), so I would suggest shortening the editor field in the example citation with "et al.".

We could optionally also introduce an "Editor" row in the tabular metadata, so the full list of editors is shown on the paper pages, but I'm not sure if that would achieve anything?

**Comment by asdogruoz** [comment]
Yes, we need an Editor row in the tabular metadata. The full list of editors are important for scientific indexing. Thank you in advance,

**Comment by nschneid** [comment]
Agreed, I think it would make sense for the tabular metadata fields to match the BibTeX fields.

**Comment by mbollmann** [comment]
I can add the Editor row pretty quickly.

> I don't see a consensus here on what we should do about the verbosity of the citations on the paper pages. I assume the important change is the BibTeX, not the example citation on the website (which, either way, is a very recent addition), so I would suggest shortening the editor field in the example citation with "et al.".

@mjpost Any thoughts on this?

**Comment by nschneid** [comment]
@mjpost Any updates?

**Comment by akoehn** [comment]
As acl style does not render the editors, so in that case, the html string should not render them as well. Otherwise, it should not be called "cite (ACL)".

**Comment by mjpost** [comment]
We have an editor field now in the page metadata block, and the bibtex contains the editor information. I agree with Arne we should remove it from the citation preview since it does not mirror the real ACL citation. Seza is this sufficient?

**Comment by shashwatup9k** [comment]
Hi all,
Thanks for this initiative and your efforts. 
It is a very important topic, so I would like to share my thoughts on this matter. 

- I think it is a good idea to render the editors in  both the _cite (ACL)_ and _citation preview_
- I have found that _@inproceedings{_  doesn't include editors in the references(screenshot attached), even when added in the [BibTeX](https://preview.aclanthology.org/propagate-editor-field/2023.semeval-1.1/) at least with _acl_natbib.bst_  and/or [_natbib_ bibliography styles](https://www.overleaf.com/learn/latex/Natbib_bibliography_styles). Hence, we need to replace __@inproceedings{_ with _@incollection{_. Otherwise, this effort will not be helpful in achieving the indexing goal. 
![indexing-issue](https://github.com/acl-org/acl-anthology/assets/7556388/2bb7bae2-7aaa-48a5-a267-fd38148995cf)

P.S.: I believe ACL or non-ACL conference/workshop proceedings are collections of papers. So, it would be good if we make the needful changes. 
 Many thanks!

**Comment by mbollmann** [comment]
@shashwatup9k Do you know of any citation style, for a major conference or journal, that displays the full list of proceedings editors for conference papers? I'm genuinely curious, because I feel this would be a very unpopular change, as it blows up the size of the references enormously.

Either way, a discussion about changing the BibTeX style doesn't really belong here (but probably in https://github.com/acl-org/acl-style-files?), as it is unrelated to the Anthology.

I definitely disagree that we should change the bibtype from `@inproceedings`. It is intended precisely for conference papers, so is the most appropriate entry type.

**Comment by akoehn** [comment]
Agree with @mbollmann.  The anthology provides correct metadata in the bibtex file, the consumer (in this case the latex style) decides how to use it.

The "collection" of papers for a conference are the *proceedings* (hence e.g. "proceedings of ACL 2025"), so, as Marcel wrote, inproceedings is the correct bibtex type.

It seems to me that whatever process is indexing the metadata should not use the bibliography in papers but the original source to get all relevant data if this is important.

**Comment by shashwatup9k** [comment]
Yes, here are some references (sorry if I didn't get your points correctly):

- http://www.lrec-conf.org/proceedings/lrec2018/bibtex.html
- http://lrec-conf.org/workshops/lrec2018/W11/bibtex.html
- http://www.lrec-conf.org/proceedings/lrec2016/bibtex.html
- http://www.lrec-conf.org/proceedings/lrec2014/bibtex.html

Since 2020 ELRA/LREC also removed the editors' information from the BibTeX when they moved to the ACL anthology or the Sthe START account changed the BibTeX stylesheet (My understanding is only speculative. Nicoletta Calzolar or Khalid Choukri or LREC editors can provide better inputs).

Many thanks!

**Comment by nschneid** [comment]
@shashwatup9k Thanks for your comment—I think the point is that the Anthology is responsible for the BibTeX and how the metadata is listed on the Anthology website. Both of those will be updated with this change. What goes into the PDF (including the bibliography rendering) is not in the Anthology's purview.

**Comment by akoehn** [comment]
> Both of those will be updated with this change.

Just to be clear, the "cite (ACL)" should still mirror the acl style, which does not show the editor.

**Comment by nschneid** [comment]
May I suggest merging these changes, and then we can reevaluate what is needed to support indexing?

**Comment by mbollmann** [comment]
#2798 depends on a decision on "Cite (ACL)". It seems we're in agreement that it should mirror ACL style, which (with the editor change) it currently does not, so that fix should be implemented first IMHO.

**Comment by nschneid** [comment]
OK sure

**Comment by mbollmann** [comment]
Pushed this to #2798 now.

**Comment by asdogruoz** [comment]
I agree with Atul's comments and suggestions. The current format is not in accordance with the scientific indexing practices. The editors should be acknowledged and (@incollection) bib format seems to be right format for this purpose. Thank you in advance,

**Comment by mbollmann** [comment]
@asdogruoz What do you mean by "format" now, the bibliographic information as provided in BibTeX, or the citation style as it appears in papers? `@incollection` is just the semantically wrong type for conference papers, and if you are talking about how the citation is rendered, this is outside the purview of the Anthology, as previously mentioned.

**Comment by shashwatup9k** [comment]
Hi all, thank you for sharing your thoughts and updating my information!
My intention was to propose a potential solution in order to avoid creating new issues in multiple places, including "_acl-style files," "_ACLPUB_," and "_ACLPUB2." I completely understand @nschneid, @mbollmann, and other points.

In this revised scenario, I believe that ACL-ORG could potentially address this matter exclusively within the "_acl-style files" and "_ACLPUB_" templates. At least this will work for ACL and non-ACL events' papers/proceedings (either organisers/publication chairs use _START_ or _ACLPUB2_ for compiling the proceedings). Maybe @mjpost and/or another team member can fix this matter using the same PR (if it is possible). However, this solution may not be applicable on a broader scale, such as at ICML, NeurIPS conferences, or in the LaTeX-style files of other journals.  Additionally, it's worth mentioning that editors will not be cross-referenced in papers' citations from other conferences or journals.

Thank you!

**Comment by nschneid** [comment]
I assume indexing services (SCOPUS, Web of Science etc.) rely on metadata such as BibTeX, so improving the Anthology pages & BibTeX will have an effect, right? ICML, NeurIPS, etc. are not published in the ACL Anthology, so any proposed changes for BibTeX from those venues would have to be taken up with the respective organizations.

**Comment by nschneid** [comment]
TBC, the changes in #2798 as I understand it are:

Any paper within a proceedings (conference or workshop) in the ACL Anthology will include the editors of the proceedings on its Anthology page, and in the BibTeX (with the `@inproceedings` entry type as usual). Therefore, metadata used by indexing services will have the editors listed for all papers of the proceedings.

As is always the case with BibTeX, how it translates to a human-readable bibliography entry in a PDF depends on the style (.bst file) of the citing venue. Style files are not under the control of the Anthology.

**Comment by mbollmann** [comment]
> TBC, the changes in #2798 as I understand it are:
> 
> Any paper within a proceedings (conference or workshop) in the ACL Anthology will include the editors of the proceedings on its Anthology page, and in the BibTeX (with the `@inproceedings` entry type as usual). Therefore, metadata used by indexing services will have the editors listed for all papers of the proceedings.
> 
> As is always the case with BibTeX, how it translates to a human-readable bibliography entry in a PDF depends on the style (.bst file) of the citing venue. Style files are not under the control of the Anthology.

That's exactly my understanding too.

**Comment by nschneid** [comment]
Editors are now incorporated! See e.g. https://aclanthology.org/2023.semeval-1.8/

Thanks to @asdogruoz and @shashwatup9k for suggesting the change and @mbollmann for leading the implementation.
