### ISSUE TITLE
Missing author data on early CL journals

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#281]
Authors are part of the titles, rather than having author fields. See for example: https://aclweb.org/anthology/events/cl-1979/

**Comment by davidweichiang** [comment]
Also, some of these "papers" are entire issues of Finite String and have the entire table of contents in the title!

**Comment by davidweichiang** [comment]
Oh, J79 even includes two years of the ACL conference...IMO, it should be totally reorganized, but I'm not sure if that's disallowed because of, e.g., DOIs. Something like:

```
J74-1     Computational Linguistics
J74-2     Finite String
J74-3     Finite String
J74-4     Finite String
J74-5     Finite String
J75-1     Computational Linguistics
J75-2     Finite String
J75-3     Finite String
J75-4     Finite String
J75-5     Finite String
J75-6     Finite String
J75-7     Finite String
P75-1     Proceedings of ACL
J76-1     Computational Linguistics
J76-2     Finite String
J76-3     Finite String
J76-4     Finite String
J76-5     Finite String
J76-6     Finite String
J76-7     Finite String
P76-1     Proceedings of ACL
J77-1     Computational Linguistics
J77-2     Finite String
J77-3     Finite String
J77-4     Finite String
J77-5     Finite String
J77-6     Finite String
J77-7     Finite String
J78-1     Computational Linguistics
J78-2     Finite String
J78-3     Finite String
J78-4     Finite String
J78-5     Finite String
J78-6     Finite String
J78-7     Finite String
J79-1     Computational Linguistics
J79-2     Finite String
J79-3     Finite String
J79-4     Finite String
J79-5     Finite String
J79-6     Finite String
```

**Comment by mjpost** [comment]
I don't think we have DOIs for these yet (there's nothing in the XML), so straightening this out would be great. Using `-{2+}` as designators for Finite String seems good to me.

**Comment by davidweichiang** [comment]
The amount of material in J79 is amazing. One of the conference proceedings even has photos.

Maybe should we do the reorganization such that no old numbers are reused?

If we create new papers in existing files, will it just work?
If we create new files, does some index somewhere else need to be updated?

**Comment by davidweichiang** [comment]
J79-1078, J79-1079, and J79-1080 are duplicates of T78.

**Comment by mjpost** [comment]
I can't imagine these are much linked, but jumping to new numbers is cleaner.

If we split up PDFs, name them appropriately (e.g., J79-2012), and create XML entries for them, it should just work. But I think I am misunderstanding your question.

I wonder if Finite String issues should just be listed as a single item. There are clearly authored articles within them and it would be a shame not to credit that, but on the other hand, I'm not sure how to create entries for filler material in between. Maybe the entire issue is analogous to the full proceedings (e.g., J79-3000), and then we create individual entries for authored articles within that matter. This sounds like a lot of drudgery. I will look for someone to do it.

I am going to look for someone to do this.

**Comment by knmnyn** [comment]
Hi Matt, all:

An additional issue is that the J79 issues don't all occur in 1979 -- many
occurred earlier.  Finite String should ideally be relegated to a different
prefix (we had 'F' reserved for them, but it was not used) but perhaps it
is better kept within the 'J' series.

It is a lot of work and it wasn't clear at the time whether there would be
much benefit.  I decided not to pursue these issues to focus on more timely
problems.

**Comment by davidweichiang** [comment]
Here's what I gathered from looking at this more closely.

- The Finite String was sort of embedded in AJCL (for example, the first page of a FS issue is a colophon for AJCL) so I think it makes sense to keep them together and in order.

- The Finite String had research articles in it; I don't understand what distinguished a FS article from an AJCL article.

- To save money, there are some AJCL articles that have FS items appended to the end of them (see, e.g., J79-1062).

- Not only does the material in J79 go earlier than 1979, actually none of it was technically in 1979, as the journal took a one-year hiatus.

- The first five volumes of AJCL, 1974-1978 inclusive, were published on microfiche only. Papers in these years are cited by microfiche number, not issue number, and the microfiches are numbered consecutively across years (microfiche n corresponds to J79-1000+n).

I have two suggestions:

- Keep the numbering as-is, but retitle the FS articles as "The FINITE STRING, Volume v, Number n" and move the table of contents into the `abstract` field. Similarly, when a microfiche is the proceedings of a conference/workshop, put the contents into the `abstract` field.

- Renumber microfiche mm in year yy as Jyy-mm. So, J74-0100, ..., J74-1400, J75-1500, ... J75-3600, J76-3700, etc. There will be no collisions because there were no issues dated in 1979. Then, if a microfiche has multiple papers, they could be broken out into PDFs with their own numbers.

**Comment by davidweichiang** [comment]
It's a little hard sometimes to distinguish between technical articles and news articles, but I count about 35-40 authored papers, which include research papers, book reviews, opinion pieces, etc. In some cases I'm wondering if these were just AJCL papers that weren't long enough to fill their own microfiche, so they were stuck into the FS.

ACL 1975 adds another 30 papers; TINLAP 2 adds some more, but those are already in the Anthology. So in all, there are about 75-80 papers that are not properly indexed because they are embedded inside bigger files.

**Comment by mjpost** [comment]
I like this approach. @davidweichiang, unless you are keen to do this yourself, I will ping someone on the volunteer list.

**Comment by davidweichiang** [comment]
I can do it. I don't think it will take that much (more) time.

I'll ask around a bit to try to find out what the status of technical articles in FS was.

Also, it appears that the way to cite articles in these years is not by volume and issue, but by microfiche number. The BibTeX would be something like:

```
@article {key,
  title = ...,
  author = ...,
  journal = "American Journal of Computational Linguistics",
  month = "April",
  year = "1977",
  note = "Microfiche 123",
  pages = "123--456",
```

Can we add a `note` field to the XML?

**Comment by mjpost** [comment]
Sounds good to me. @mbollmann can `note` be pushed through to the BibTeX?

It turns out we have a ton of early CLs on a shelf here, left by Kenneth W. "C." (along with a stack of his patents :)). One of them even has the microfiche! It seems that sometimes The Finite String was distributed separately, for example, Volume 18 Number 4 (Dec. 1992), which is not in the Anthology. There is also a Dec. 1983 Special Supplement to AJ of CL, a Directory of Graduate Programs in CL, also not in the Anthology. I'll queue these up to be added.

![IMG_5426](https://user-images.githubusercontent.com/455256/56900386-b4415d80-6a63-11e9-8392-fac6152bd50b.jpg)

**Comment by davidweichiang** [comment]
The tables of contents (e.g., https://aclweb.org/anthology/J80-1000) sometimes list a "microfiche supplement" that does not appear in the Anthology. Maybe you've discovered one of those.

**Comment by davidweichiang** [comment]
@mjpost could you take a look at #285, especially the questions in the discussion there? Thanks.
