### ISSUE TITLE
Question about ACL profiles - needed for changes to OpenReview

### ISSUE THREAD

**Issue by jkkummerfeld** [acl-org/acl-anthology#3112]
ARR is working with the team at OpenReview to add to OpenReview profiles a place for people to record a link to their ACL Anthology profile.

Is this regex an accurate description of the URLs for ACL Anthology profiles? It will be used to constrain what people can enter into the box.

`^https:\/\/aclanthology\.org\/people\/[a-z]\/.+$`

Once people fill in these links in their profiles it will be very helpful information for us.

**Comment by mbollmann** [comment]
That looks correct, and could currently be constrained even further to

    ^https:\/\/aclanthology\.org\/people\/[a-z]\/[a-z0-9\-]+/$

However, you might want to consider making the regex _less_ strict and just using:

    ^https:\/\/aclanthology\.org\/people\/.+$

This is because we have long considered using ORCIDs as part of the URL to disambiguate authors (#623), and even though things are moving slowly, there’s already a concrete proposal for this (#1179) that would drop the "single letter" part from the URL.

**Comment by jkkummerfeld** [comment]
Good to know! We'll go with the more flexible one then.
