### ISSUE TITLE
Ingestion Request: PROPOR (2)

### ISSUE THREAD

**Issue by hgoliv** [acl-org/acl-anthology#3229]
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

propor

### Volume Title

[Main Volume] title: "Proceedings of the 16th International Conference on the Computational Processing of the Portuguese Language (PROPOR 2024) -- Main Conference"; [Co-Located Events Volume] title: "Proceedings of the 16th International Conference on the Computational Processing of the Portuguese Language (PROPOR 2024) -- Co-Located Events"

### Venue Name (only if you are submitting a new venue)

International Conference on the Computational Processing of the Portuguese Language (PROPOR)

### Venue Website (only if you are submitting a new venue)

https://propor2024.citius.gal/

### Supporting Information

An archive with both volumes can be found here: http://eden.dei.uc.pt/~hroliv/propor2024/propor2024_data.tgz

The Main Volume has been published but should be replaced because some minor fixes were made.
The Co-Located Events volume has not been published yet.

**Comment by anthology-assist** [comment]
@hgoliv Thank you for the issue. What has been changed/updated in the main volume? If possible we'd like to avoid a re-ingestion.

**Comment by hgoliv** [comment]
I'm sorry, I really didn't know that it would make such a difference, so I did not keep track of the changes. And it's been so long that I just remember that one paper had to change the title, because the one on the PDF was different from the one in the metadata. One or two papers had minor changes in the References, and there might have been also minor changes in the front matter. But, to be honest, I'm not completely sure if this is it, nor which papers were changed. I'm so sorry...

Best,
Hugo

**Comment by anthology-assist** [comment]
@hgoliv In that case I will leave the ingested main volume as is, the individual problematic paper authors can submit correction tickets in order to make individual changes.

The colocated events will be ingested.

**Comment by hgoliv** [comment]
I am sorry, but is it really impossible to ingest the main volume again?
I tried to confirm the changes, and I could confirm there were indeed changes in the Front Matter (affiliations and alignments), but I could not confirm what were the papers with changes, especially the one that changed the title.
I also don't think that the authors will create such tickets, not only because they don't know how to, but especially because I told them that the problems would be fixed at the time of publishing Volume 2...

Best,
Hugo

**Comment by hgoliv** [comment]
Hi,
I would like to know what is the status of this request.

By the way, some authors have told me that they can already access the volume 2 of the proceedings through this link: https://aclanthology.org/2024.propor-2.0.pdf
But I find no other way to get them. Is it possible that their ingestion went wrong?

Thanks,
Hugo Gonçalo Oliveira

**Comment by leoalenc** [comment]
> Hi, I would like to know what is the status of this request.
> 
> By the way, some authors have told me that they can already access the volume 2 of the proceedings through this link: https://aclanthology.org/2024.propor-2.0.pdf But I find no other way to get them. Is it possible that their ingestion went wrong?
> 
> Thanks, Hugo Gonçalo Oliveira

Hi! @anthology-assist, I'm one of the authors of Volume 2, which also has the link below, besides the one mentioned by @hgoliv:

https://aclanthology.org/volumes/2024.propor-2/

Differently than the former link, this one directs to a page with a list of all papers, which one can download individually. However, it seems that there is a problem with some papers. They seem to be invisible to the search engine.  For example, when I search for _Nheengatu_, my paper [A Universal Dependencies Treebank for Nheengatu](https://aclanthology.org/2024.propor-2.8/) is not retrieved, although the paper [by Pinhanez, Cavalin, and Nogima](https://aclanthology.org/2024.propor-2.7/) in the same Volume 2 is retrieved when I search for this keyword. The same problem happens when I search for the term _Guajajara_, which occurs in the  paper 
[Building a Language-Learning Game for Brazilian Indigenous Languages: A Case of Study](https://aclanthology.org/2024.propor-2.5/) by Gustavo Polleti, which is not retrieved.
Both my paper and Polleti's (in the ACL anthology version) are also not retrieved by Google, differently than the other mentioned paper by Pinhanez, Cavalin, and Nogima.
If these are real issues, I hope they are fixed, for which I would thank in advance. 
Best, Leonel Figueiredo de Alencar

**Comment by anthology-assist** [comment]
Closed #3275

**Comment by akoehn** [comment]
Regarding the search: the search is provided by Google and we do not control their search index nor their update process, so all you can do is wait and if there is a problem with the search (and not our anthology pages), raise the problem with Google.
