### ISSUE TITLE
Author Metadata: {Jonathan Kropko}

### ISSUE THREAD

**Issue by jkropko** [acl-org/acl-anthology#3257]
### Author Pages

NA

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [ ] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

My name is Jonathan Kropko. There is no author page when realizing a search in the ACL system looking for my name.

Google scholar for reference: https://scholar.google.com/citations?user=wFgLdqUAAAAJ&hl=en&oi=sra

**Comment by akoehn** [comment]
After a look at your profile, I see no ACL publication. In case we do host a publication authored by you but it does not have your name, please file a specific ticket or directly a PR. otherwise it is expected that there is no author profile for you.

P.S. this is the second request like this in a short time, is there an underlying cause for people assuming they should have a profile page at the anthology?

**Comment by mbollmann** [comment]
@akoehn OpenReview has just added the option to add your ACL Anthology profile, and ARR has requested that people update it. However, the instructions on OpenReview also say that this is optional.

**Comment by akoehn** [comment]
For some reason I was never invited to participate in ARR -- given all the twitter messages, it might be not a bad thing though.
