### ISSUE TITLE
Committing to master

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#367]
We have a growing group of people with write access to the `master` branch. This is great! But we might want to treat it with a bit more care. One thing Github supports is *requiring* a code review before merges against `master` (this just means someone has to click "Approve"). This seems like a good idea to me, but may be an impediment. Share your thoughts here.

**Comment by mbollmann** [comment]
A related comment: It happened many times now that I've seen PRs in my e-mail notifications that I marked to take a look at, but that were subsequently merged before I had a chance to do so (usually in less than half a day). While I like quick turnaround times, I think it's good to give people a chance to review/add comments before merging non-trivial changes.

**Comment by davidweichiang** [comment]
I'm not able to push directly to `master`. I have to make a PR and pass the tests. So I may be one of the main culprits for the too-fast PRs. Sometimes the changes are so minor that I'm sure that no one will have a problem with it.

**Comment by akoehn** [comment]
I'm for this method.  Even if the PR does not need to be changed, it gives everyone some time to look at it and understand it (see e.g. #363).  There is very rarely a *need* for fast merges except gratification.

@davidweichiang you could make a PR and then let somebody else approve and merge it. That way, it would not be more work for you than it is now. (And I think that the repository is set up so that nobody can push directly to master.)

**Comment by mjpost** [comment]
@davidweichiang, I'm not sure why you weren't able to push.

I have now enabled this setting. All pushes must now be made to a branch, and then a PR initiated from the branch against master. The branch cannot be merged until one person approves it. There is a mechanism for requesting reviews if you want a specific person to do them. I think this is good practice.
