### ISSUE TITLE
LREC-COLING 2024 bibkeys do not follow the usual pattern

### ISSUE THREAD

**Issue by texttheater** [acl-org/acl-anthology#3688]
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

Almost all LREC-COLING 2024 papers include two rather than one title word in their bibkey. This would be expected in case of clashes, but in most cases there are no clashes.

For example, [Vella et al. (2024)](https://aclanthology.org/2024.lrec-main.1420/) has `vella-etal-2024-towards-corpus` instead of `vella-etal-2024-towards`, although it is the only paper in the Anthology with the latter key as a prefix.

@mbollmann [reckons](https://mastodon.social/@mbollmann@sigmoid.social/112829897171675046) the `create_bibkey` method was accidentally run twice during ingestion, resulting in these longer-than-expected bibkeys.

Would it be possible to correct this? The near-perfect predictability of bibkeys from the authors, year, and title is a feature of the Anthology bibfile I've come to rely on and I'm probably not the only one.

**Comment by mbollmann** [comment]
I can trace this back to commit [19d3586](https://github.com/acl-org/acl-anthology/pull/3304/commits/19d35862f4a3d4dd276b1daedb476d10c1666803) when @anthology-assist reingested the main volume. Before this, the bibkeys looked correct. I suspect that since the volume with all the bibkeys already existed, the library generated the two-word bibkeys to ensure uniqueness.

This is a mistake during ingestion for which we should probably have some detection mechanism. @mjpost @akoehn

**Comment by mjpost** [comment]
Yes let's fix this. @anthology-assist can you do that?

In fact anyone could fix this with their own PR:

1. cat the file, grep -v the bibkeys, sponge it to the original file

2. Run write_bibkeys -c

3. Commit / push / create PR

**Comment by mjpost** [comment]
Actually I just did this. I also fixed the logic for generating volume bib keys, which will now follow the pattern `{collection_id}-{volume_name}-{year}`, e.g., `lrec-coling-main-2024`. This fixes a bug where volumes would be assigned double years, e.g., `lrec-2024-2024`.
