### ISSUE TITLE
TPMS cannot process author pages

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#377]
[TPMS](http://torontopapermatching.org/webapp/profileBrowser/) has an option to give a URL of a page with links to PDFs. But it doesn't work on an Anthology author page. I'm guessing, but am not sure, that it's because the links to PDFs do not actually end in ".pdf".

**Comment by mjpost** [comment]
What if we added a per-author BibTeX page? e.g., https://aclweb.org/anthology/people/d/david-chiang/all.bib.

**Comment by mjpost** [comment]
We could also just add the `.pdf` to the link on the PDF button (these URLs resolve), but I'd want to see what @mbollmann thinks.

**Comment by akoehn** [comment]
I'm on a train right now, so limited search ability.  There was an issue where @knmnyn advised against using `.pdf` in links.  I'm not sure whether we should link to a single PDF using two different URLs.

I like the per-author bibtex file, if it is little work -- we would get mods and endnote for free.  OTOH, I know no other use case than TPMS (maybe somebody creates their webpage from bibtex entries?)

**Comment by mbollmann** [comment]
#179 was the issue.

I would be hesitant to change this without thorough consideration; there could be many potential pitfalls that I'm not fully aware of. One that comes to mind is indexing by Google Scholar and the like – will the URLs with and without `.pdf` be recognized as the same file? I'm not even sure it's a good idea that URLs with `.pdf` currently *do* work without rewriting to the canonical one...

**Comment by mjpost** [comment]
We could A/B test it :)

I think it makes sense for canonical URLs to be extension-less, but also that our "PDF" button could link to a version with ".pdf". Our previous Scholar issues were due to having link and linked on different domains. It seems to me that having the file type as part of the link might even strengthen the association in Google's index.

But I also think it'd be helpful to build a metadata page for each author (#314). This could also be useful for the ACL 2020 folks who want to automate TPMS.

**Comment by akoehn** [comment]
> I think it makes sense for canonical URLs to be extension-less, but
> also that our "PDF" button could link to a version with ".pdf".

Were would the canonical URL still appear? Only in the bibliographic
information, i.e. bibtex?

Having the .pdf in the PDF links would also ease mirroring as no rewrite
rules are needed for the mirror.  The canonical URL would still point to
the anthology in the mirror (otherwise it would not be canonical).

**Comment by mjpost** [comment]
Canonical links are still used externally.

**Comment by akoehn** [comment]
As the canonical URL should be used for external linking, we could add a "copy permanent URL" button to ease linking by third parties such as researchers wanting to link from their website.

**Comment by mbollmann** [comment]
> As the canonical URL should be used for external linking, we could add a "copy permanent URL" button to ease linking by third parties such as researchers wanting to link from their website.

People are notoriously bad at following instructions, though. I guarantee that many will open the PDF and copy the URL from the browser bar. That's why I think that the URLs with `.pdf` should at least explicitly redirect to the canonical format (which they don't do right now!). But even so, I'm sure that linking to a variant with `.pdf` will guarantee that some people use it in their citations.

**Comment by davidweichiang** [comment]
I agree that people won’t use the button, nor should the be expected to. How about hidden links to the .pdf URLs? I wonder if TPMS would recognize that.

**Comment by mjpost** [comment]
I tested that added the PDF links works: <https://www.aclweb.org/anthology/people/m/matt-post/tpms.html>

```html
<a href="https://www.aclweb.org/anthology/N19-1090.pdf">paper</a>
<a href="https://www.aclweb.org/anthology/W18-1820.pdf">paper</a>
<a href="https://www.aclweb.org/anthology/W18-6300.pdf">paper</a>
```

I would guess they are doing something simple like looking for `href` attributes that point to something with a `.pdf` extension.

**Comment by davidweichiang** [comment]
IMO the simple hack would be for author pages to have `<a href=... style="display: hidden">` links in addition to the existing links.  Would there be any downside to that?

**Comment by mjpost** [comment]
That worked, too (though it's `display: none`).

**Comment by akoehn** [comment]
> IMO the simple hack would be for author pages to have <a href=... style="display: hidden"> links in addition to the existing links. Would there be any downside to that?

Do the .pdf URLs currently serve a 301 to redirect to the version
without?  Otherwise, some other scrapers might not see that we are
actually linking to the same paper twice.  OTOH, I don’t even know a
downside that might have …

The only other thing I could think of would be SEO stuff, i.e. search
engine disliking hidden links.  I have zero clue about that topic (and
whether they do or not).

Unless someone finds a real downside, this seems to be both the best and
the easiest solution to me.

**Comment by mbollmann** [comment]
> Do the .pdf URLs currently serve a 301 to redirect to the version without? 

They don't, but I really believe that they should.

(Though there's a small chance it might affect TPMS's processing maybe?)

**Comment by mjpost** [comment]
Okay, I tested this redirect (from ".pdf" to canon), and it works.

I also put the new page version in place for [my page](https://aclweb.org/anthology/people/m/matt-post/) and tested it at TPMS. It works very nicely.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/455256/60021815-a6254d00-9660-11e9-93d0-03e51c5a2818.png">

If someone wants to approve #377 (and maybe #422 while you're at it?) we can close this issue out!
