### ISSUE TITLE
DBLP update

### ISSUE THREAD

**Issue by cfedermann** [acl-org/acl-anthology#4]
**S/N:** 4
**Title:** DBLP update

**Comment by villalbamartin** [comment]
Could you expand on this ticket? Is it still an open issue?

**Comment by knmnyn** [comment]
Hi all:

Christian basically ported a number of the issues that were in a Google
Spreadsheet into the Github Issues.  This issue is about ensuring that DBLP
has the recent metadata records for the workshops / conferences that are
ingested in the ACL Anthology.

We don't have this working at the moment, but DBLP seems now able to crawl
the respective data from us.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by knmnyn** [comment]
Closing issue.
