### ISSUE TITLE
Show Volumes gets author order wrong

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#58]
This page still has the authors in the wrong order:

https://aclanthology.coli.uni-saarland.de/volumes/proceedings-of-the-2018-conference-of-the-north-american-chapter-of-the-association-for-computational-linguistics-human-language-technologies-volume-1-long-papers

Related to #47 (Show Events gets author order wrong) but doesn't seem to be solvable in the same way.  Likely some param being passed in that needs to be unset.

**Comment by knmnyn** [comment]
Reported by Drago.

**Comment by villalbamartin** [comment]
I looked into this. It is an interesting problem: we inserted the authors in a specific order, but that shouldn't have a meaning by itself - just because we inserted the records in a certain order, that shouldn't really have a meaning for the database.

Should we add a field `author_order` to the table `papers_people`? Apparently, the fact that PostgreSQL returns the authors in the same order as in the insertion is no guarantee that they will _always_ be returned in that same order.

**Comment by knmnyn** [comment]
This as a good idea.  It's not urgent but what we have now is not actually
standard XML since the order of sibling fields in meaningful.

>

**Comment by knmnyn** [comment]
Reported again for below:
 
> We have a paper published in ACL 2018, named "Recursive Neural Structural Correspondence Network for Cross-domain Aspect and Opinion Co-Extraction". The paper ID is P18-1202. However, the order of the authors displayed on acl anthology is not correct, as shown in the following screenshot.

> The correct order should be "Wenya Wang | Sinno Jialin Pan". The wrong ordering results in incorrect bibtex e.g. in DBLP that may affect following citations. Could you help to update the author order as stated? (The wrong ordering only appears in this proceeding list.)

**Comment by knmnyn** [comment]
Could this be fixed in the same way as that for #47 ? 

> I took out the includes clause that was eager loading the people connected join table, which had the side effect of reordering the authors on the volume page.

**Comment by mjpost** [comment]
Closing this as deprecated.
