### ISSUE TITLE
link to pdf returns 404 error

### ISSUE THREAD

**Issue by krishnamrith12** [acl-org/acl-anthology#595]
link to pdf returns 404 error
Link: https://www.aclweb.org/anthology/W19-75

**Comment by mjpost** [comment]
The problem is that these are volume pages. This one can be found here: https://www.aclweb.org/anthology/volumes/W19-75/. Can you report where this was linked from?

**Comment by akoehn** [comment]
Sorry to highjack this, but what is the canonical URL to volumes?

**Comment by mjpost** [comment]
I am not sure what the answer to this is. The pdf is at `/W19-75.pdf`, so `/W19-75` makes sense. But the volumes are all built and exist under `volumes/` and it makes sense to have them there as well, since they are distinct in type from papers.

**Comment by mjpost** [comment]
Digging a bit deeper, I'd say

- /volumes/W19-75 should be the volume canonical, a page containing links to all papers in the volume (currently in place)
- /W19-75 should 301 to it (this PR), since for a while we must have been generating links to this
- /W19-7500 is the frontmatter canonical (current in place)
- /W19-75.pdf should serve the PDF (currently in place)

**Comment by krishnamrith12** [comment]
The link which was originally returning 404 was the href to the pdf(full) button present in https://www.aclweb.org/anthology/events/ws-2019/#w19-75

The link is active now. I think the issue can be closed now.

**Comment by akoehn** [comment]
In that case we should generate the correct URL directly and not rely on a 301.
