### ISSUE TITLE
Video links need to show up and be faceted searchable as in the attachments

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#64]
In the original anthology (e.g., ACL 2015 , https://aclweb.org/anthology/P/P15/) video links show up.
We need these to show up in the current Anthology too.

**Comment by villalbamartin** [comment]
I looked into it, and here's some extra info. I'll take as an example paper P15-1002, "Addressing the Rare Word Problem in Neural Machine Translation" (database id 22640). This paper has a video link in the original Anthology, but it doesn't have one in the current one.

I've looked in the database, and I couldn't find any reference to the link. There is a `video` field in the XML, though, but the `xml_import.rake` script doesn't do anything with it.

Here's my proposal about how to move forward, along with the reasons why I decided to ask for input rather than just jumping into it:

1. We add a `video` field to the database.
2. We either re-ingest the entire database, or write a script that interfaces directly with the database and adds the missing links.

Regarding point 1: I think there's a mechanism in Ruby to modify the structure of a database. We need to do it that way because otherwise no one can rebuild the database properly from scratch. We have made this mistake once, and in fact I'll open an issue for that as soon as I'm done here because I don't think anyone noticed. If anyone is familiar with Ruby, this could go faster than me starting from scratch.

Regarding point 2: I think writing a script that adds the missing data might be better. I seem to remember that Google once complained because we regenerated the database and that triggered a cascade of refresh, since the internal ID changed and they somehow rely on that.

**Comment by knmnyn** [comment]
Hi Martín, all:

point 1.  Rails uses DB migrations to allow anytime update of the DB
schema.  This is the preferred way to build the database in Rails.
point 2.  That's fine as a one-off job.  I'm worried the current slowness
of the application is due to DB overheads.  Can we check whether any of
that is the case?

**Comment by knmnyn** [comment]
point 1.  Rails uses DB migrations to allow anytime update of the DB schema.  This is the preferred way to build the database in Rails.
point 2.  That's fine as a one-off job.  I'm worried the current slowness of the application is due to DB overheads.  Can we check whether any of that is the case?

(Redoing since the email to github, didn't seem to propagate on the thread.  Sorry if it ends up being duplicated)

**Comment by mbollmann** [comment]
For the record, I'm currently handling this in the static rewrite by merging `<video>` elements with other types of attachments during the XML-to-YAML conversion (#129). We can probably close this once the static rewrite is completed.
