### ISSUE TITLE
Names in BibTeX not rendered properly in PDF output

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#655]
The first entry in our `anthology.bib.gz` is [W19-8500](https://www.aclweb.org/anthology/W19-8500/):

```bibtex
@proceedings{ws-2019-international-resources,
    title = "Proceedings of the Second International Workshop on Resources and Tools for Derivational Morphology",
    author = "{\v{S}}ev{\v{c}}{\'\i}kov{\'a}, Magda  and
      {\v{Z}}abokrtsk{\'y}, Zden{\v{e}}k  and
      Litta, Eleonora  and
      Passarotti, Marco",
    month = "19--20 " # sep,
    year = "2019",
    address = "Prague, Czechia",
    publisher = "Charles University, Faculty of Mathematics and Physics, Institute of Formal and Applied Linguistics",
    url = "https://www.aclweb.org/anthology/W19-8500",
}
```

The names are

> Magda Ševčíková, Zdeněk Žabokrtský, Eleonora Litta, Marco Passarotti

but in an ACL 2020 Overleaf document I have renders like this:

![image](https://user-images.githubusercontent.com/455256/68898906-71449000-06fe-11ea-98b2-9373e2ad6c97.png)

**Comment by mbollmann** [comment]
`author` is not the correct field for a `@proceedings` entry; it should be `editor`.

The culprit is here, where the `editor` field is explicitly changed to `author`:
https://github.com/acl-org/acl-anthology/blob/48be50a6935139ce7b6139d0ee016c02056a700b/bin/anthology/papers.py#L107-L109

This is presumably done for having it render correctly on the website, but produces the wrong result in this case, as it is the "front matter paper" from which the volume BibTeX entry is generated.

We can add an exception to BibTeX generation that changes `author` back to `editor` when the bibentry is `@proceedings`, which is a two-line fix, but feels a bit messy. Alternatively, we could change the site rendering to use the `editor` field when `author` is empty, which is potentially quite a bit more involved.
