### ISSUE TITLE
Remove the publisher line?

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#683]
Does the publisher line matter for `@inproceedings` bibtex types? My citation sections are filled with "Association for Computational Linguistics" tetragrams. We could consider removing these lines from `https://www.aclweb.org/anthology/anthology.bib.gz`, but maybe that information is important to include in some settings.

**Comment by mbollmann** [comment]
If that information is undesired, it should be removed from the bibliography style instead, no?

It is indeed optional for `@inproceedings`, but as it can be easily removed by the bibliography style, but not easily added when it is not there, I would be in favor of keeping it in.

**Comment by akoehn** [comment]
Marcel Bollmann writes:

> If that information is undesired, it should be removed from the bibliography style instead, no?

Not if it is only undesired for ACL publications.  If you also want to
cite other @inproceedings entries, this decisions needs to be on a
per-paper basis.


That said, I would not remove this entry from the bibtex withouth
serious considerations first.  Having ACL as publisher for the ACL
conference seems to be obviously redundant, but that is not as clear for
all others:

 - Will everyone know whether ANLP proceedings are published by ACL?
 - who plublishes LREC?
 - Random Workshop (colocated with ACL): Is it otherwise obvious that
   ACL published the proceedings? Probably for something like
   “Repeval@ACL”, but less obvious for others.

Etc.  There is no simple delineation where to include it and where not.
My take:  If an author cares about that, they can just delete the lines
they find unpleasing.  This is not a strong opinion, just my current one.

**Comment by nschneid** [comment]
One reason to keep it in the BibTeX is that this means it is included in the Zotero import.

I agree that there are different styles an author may use on a per-paper basis (which could include abbreviating the proceedings title, omitting the month, etc.). Other tools can be used for such customizations.

**Comment by mjpost** [comment]
All right, closing this, thanks all!
