### ISSUE TITLE
Our Google search gives both PDFs and summary pages

### ISSUE THREAD

**Issue by aryamccarthy** [acl-org/acl-anthology#752]
This output is frustrating; it's a coin-flip whether search gives me a PDF or a summary.
https://www.aclweb.org/anthology/search/?q=BLEU+correlation

Can we add an automatic `-filetype:pdf` flag to the search, so we only get summary pages? It's easy to click from summary page to PDF if that's sought, but hard to click in the other direction. If I want, e.g., BibTeX, that's a pain.

**Comment by mbollmann** [comment]
I _think_ that would prevent fulltext search in the PDFs though, wouldn't it?

**Comment by akoehn** [comment]
What Marcel says.
As far as I know, this does not work with Google custom search, somebody would have to host and maintain their own search engine for that. IIRC, we had that discussion before somewhere and nobody had a good solution.

**Comment by mbollmann** [comment]
A better search solution is still on my to-do list, but other things like the ID format change took precendence. :)

**Comment by mjpost** [comment]
Yes, and see also #244. There are many reasons to move away from Google. I can't seem to find our discussion but there are many flexible tools these days and doing a custom search engine seems like a good approach. I'm going to close this for now since we are not going to address it within the Google paradigm.
