### ISSUE TITLE
Request for merging alternative author names

### ISSUE THREAD

**Issue by tttorrent** [acl-org/acl-anthology#884]
Dear all,

Apparently there are 3 of me in the ACL Anthology, I mean, there are 3 author pages in which different papers I co-authored are distributed:

https://www.aclweb.org/anthology/people/t/tiago-timponi-torrent/
https://www.aclweb.org/anthology/people/t/tiago-timponi-torrent1/
https://www.aclweb.org/anthology/people/t/tiago-t-torrent/

I find it odd since I have only one Global Profile in the START System and all those publications were produced using this same system. Would it be possible to merge all of them into one single author: Tiago Timponi Torrent (also published as Tiago T. Torrent and Tiago Torrent)?

Many thanks!

Tiago

**Comment by mjpost** [comment]
Is it

> Torrent, Tiago Timoni

or

> Timoni Torrent, Tiago

?

**Comment by mjpost** [comment]
This is an easy fix. It would expedite things if you (a) edited the `data/xml/*.xml` files yourself, to correct the first name / last name split and (b) found your entire in `data/yaml/name_variants.yaml` and added "Tiago T. Torrrent" as a variant and (c) created a PR.

Otherwise we will get to it eventually.

**Comment by tttorrent** [comment]
Hi!
It's Torrent, Tiago Timponi.
Many thanks!
