### ISSUE TITLE
Chrome plugin

### ISSUE THREAD

**Issue by ozancaglayan** [acl-org/acl-anthology#920]
Hi,

After being inspired by a discussion in twitter about always carrying along/accessing the current anthology, I started to sketch a chrome plugin to search the anthology. It currently provides a fast search through URL bar and then fires up the anthology webpage. Since I re-learn javascript once again every 5 years, it takes some time and the code may not be perfect.

Would you be willing to keep the code under here? +any suggestions on features?
I currently parse the anthology and create a restricted JSON with only author, title information. From which, a search index is created as well (I used lunrjs.com). The blobs take 40M (uncompressed).

**Comment by akoehn** [comment]
Did you have a look at aclfind.uber.space? It would probably be much easier to use the existing infrastructure than to rebuild from scratch.

**Comment by ozancaglayan** [comment]
Didn't know about that but apparently it's Python+Rust and not javascript. But thanks, at least some codes could be shared.

This is what I came up with so far:
![acl](https://user-images.githubusercontent.com/330946/87201817-06d50580-c308-11ea-87a0-d749e6ace0ac.gif)

**Comment by mbollmann** [comment]
That looks really cool, @ozancaglayan!

I don't know if I would use it personally; I think such extensions are very similar in functionality to search prefixes. For example, I've set up my browser so that typing `acl bert` will load https://www.aclweb.org/anthology/search/?q=bert, and the same thing could be implemented for [aclfind.uber.space](https://aclfind.uber.space) when it's ready. The difference of course is that your solution (i) gives the results right there in the dropdown and (ii) works fully offline.

Re: keeping the code, what'd be the advantage of keeping it in the main repo here? I'd think maintainability would be a lot easier (for you and anyone who might wanna work on it) if it were a separate repo. We could still link to it.

**Comment by akoehn** [comment]
I think there is also a protocol to show suggestions and completions in the browser bar from a specific source, e.g. the acl search.  That was what I meant with reusing the infrastructure.

**Comment by mbollmann** [comment]
Ah, right! @ozancaglayan, while the search prototype has a Python+Rust backend, the web interface itself sends GET requests via JavaScript that return JSON objects with the search results. You can see here how it's currently done (caution, messy code ...): https://github.com/mbollmann/aclfind/blob/master/html/js/search.js

So yeah, maybe that could be re-used/modified to be better integrated with the browser bar, via an extension or other means(?).

**Comment by ozancaglayan** [comment]
yes possibly. Right now everything is running client-side, which is good as well. 

I would like to have this as a way to quickly search, see the PDF and copy the bibtex into clipboard. Alternatively, it can collect bib entries in a scratchpad which i can then export/copy to clipboard as well. No persistence or bib management like zotero but a quick way to search for 6-8 papers, look at them and get a buffer of their bibtex entries.

**Comment by akoehn** [comment]
A plugin like that is certainly handy, but I would develop it in a different repository:

 - if it becomes more successful, we will have to manage PRs to the anthology in the same channel as the plugin
 - same for bug reports / the issue tracker
 - you cannot add new contributors to the plugin here because they then would all have write access to the anthology repository
 - the plugin and the anthology repository do not share any code

We can discuss ways to have better anthology APIs for this use case, but I would not host the applications themselves here.
We could, however, add links to helpful software on an anthology site.

**Comment by ozancaglayan** [comment]
Yeah sure, makes sense. Thanks for the pointers, I'll try to work on this in the next couple of weeks.

**Comment by akoehn** [comment]
Development does not happen in this repo, closing.
