### ISSUE TITLE
Erroneous capitalisation of N-gram, K-means, etc.

### ISSUE THREAD

**Issue by marcschulder** [acl-org/acl-anthology#959]
During testing for issue #953 I ran into an interesting issue with rule 6 of the [fixed-case algorithm](https://github.com/acl-org/acl-anthology/blob/master/bin/fixedcase/README.md), which says that any single character word apart from "A" will be marked as fixed case. As hyphens are treated as whitespace, this means that terms like _N-gram_ and _K-best_ receive fixed case tags. 

I found a lot (total > 200 cases) of the following:
- _N-gram_
- _N-grams_
- _N-gram-based_
- _N-best_
- _N-ary_
- _K-best_
- _K-means_

Plus a few other cases like _K-nearest_, _K-fold_, _N-th order_, _K-repeating_ or _At-Least-N_.
Some other cases might or might not be appropriate to capitalise, like _K-SRL_, _K-Service Provision_, _N-Hance_ or _Returning the N to NLP_.

I suggest changing the algorithm to treat N and K like A, as the vast majority of cases should not be capitalised.

Pull request #960

**Comment by nschneid** [comment]
I'm not sure what the best policy is here, considering that some authors use capital K and N variables in the body of the paper while others use lowercase.

**Comment by marcschulder** [comment]
Sounds like that would be something that can't be done heuristically then. I suggest being less invasive would be better than, so such characters should not be marked as fixed-caps. Theoretically individual cases could then still be marked manually, while preventing false positives.

**Comment by nschneid** [comment]
Counterargument: if neither way is more "correct" than the other, fixed-casing all of them would preserve the generalization about single-character letters, considering that even "K" and "N" are not guaranteed to be variables (e.g. https://www.aclweb.org/anthology/W15-0811.pdf). We really do need an exception for "A" because of the indefinite article.

Also, if authors really didn't want "K" or "N" capitalized they could have made it lowercase in the metadata.

I guess my feeling is that the harm of an extra capitalization of "K" or "N" as a variable name in a bibliography when the author didn't capitalize it in the body of the paper is lower than the harm of failing to capitalize "K" or "N" when it is not being used as a variable. OTOH being conservative about applying fixed-case automatically allows it to be specified on a case-by-case basis. So I see both sides here. :)

We could try for a more specialized heuristic that is context-dependent: if the next word is "nearest", "NN", "gram", "grams", or "best", then refrain from applying fixed-case to "K" or "N".

**Comment by marcschulder** [comment]
Fair points. I did consider a bi-gram solution as you propose. Downsides would be that a) we still don't know the stance of individual papers on the capitalisation in those bigrams, and b) we end up with a long tail of other k/n-bigrams that might or might warant inclusion in this rule. Maybe the rule should therefore exclude any match of "[KN][ -][A-Za-z][a-z]+" or something similar. (There were cases of "n gram" with space instead of hyphen, hence the inclusion in the regex)

Maybe what all the this boils down to is that automatic single character caps fixing is a pretty aggressive rule. The reason I would vote for  making it less aggressive is that false positives get applied every time the script is run (except titles in the exception list) while false negatives can still be added by hand and then don't get touched by the script (if I understood right).

**Comment by marcschulder** [comment]
Pull request #960 was accepted, so I guess this issues is resolved (for now)?

**Comment by akoehn** [comment]
Okay, closing it (for now) :-)
